### ISSUE TITLE
others/issuesの運用に関して

### ISSUE THREAD

**Issue by yenxrutile** [BitzenyCoreDevelopers/others#1]
Bitzenyに関する様々な問題提起、議題をストックして行くスペースです。
(基本的にBitzenyの利益になる要件)
正式なタスクにする前の準備室のような用途を期待しています。

まだ運用開始したばかりなので、より良い使い方が出来るよう、活発に意見交換、
フィードバックしていきたいです。
どうぞ宜しくお願い致します。

・今のところは、以下のような投稿を推奨致します。
　・すぐに回答が出しにくい問題提起のメモ
　・結論が出ずに停滞してしまった議論の経過保存

・暫定ルール
　・議題毎に個別にトピックを立てて下さい。
　　類似、互換する要件は適宜追記した方が良い場合もあるかもしれません。

　・一つの議題が進展しましたら、経過状況を記載して頂きたいです。
　　正式なタスク化に至ったトピックはクローズして下さい。
　　(othersの役割としてはそこまでかと思いますので)

　・isshuを立てるべきかどうか、または内容の判断に迷う事があれば、
　　discordの#general_jaやフォーラム等でお尋ねください。

　・ある程度具体化したら、公式フォーラムに"[タスク化]〇〇したい"のような
　　トピックを公開し、意見をもらった上でbitzenyのgithub wikiに正式な
　　タスクとして追加して下さい。
　　簡単な理由、経緯を添えると良いかもしれません。

以上
[随時内容更新]

**Comment by onokatio** [comment]
ついでに、問題だったり提案がまとまったら、bitzenyのほうのgithub wikiにまとめるのはどうですかね

**Comment by yenxrutile** [comment]
承知です。

**Comment by yenxrutile** [comment]
内容的には妥当な物でも、いつの間に決まった事で、誰がやるねんとなりそうなので、ある程度
良い感じになった段階で、公式フォーラムに"[タスク化]〇〇したい"みたいなトピックを立てて、
お披露目し、各種レスポンスをもらった上でwikiに追加してはどうかと考えました。

もう少し諸々整理がついたら、公式フォーラムの方にこちらのスペースの紹介をしようと思っています。
五所川原さんもタスク準備室のスペースを探していたようでしたので、お声掛け致しました。
～～～
3/6追記：
discord連動、フォーラムの案内で導線強化されましたので、状況に合わせて
対応して行きたいと思います。ご協力誠にありがとうございます。

**Comment by yenxrutile** [comment]
安定運用されていると思いますので、一旦クローズ致します。
問題提起が発生した場合は、再オープンして頂ければ。
