### ISSUE TITLE
公式プール設置のメリット、デメリット

### ISSUE THREAD

**Issue by yenxrutile** [BitzenyCoreDevelopers/others#14]
しばしば議題に挙がって来そうなので、こちらに情報を集積して行きます。
また、その時の状況、環境によってはメリット、デメリットも変わって来るかもしれません。

～内容はのちほど～

**Comment by yenxrutile** [comment]
■メリット
・管理のしやすさ、51%問題対策
・fee高めでも利用してくれるかも。CoreDev向けの収益。

■デメリット
・個人運営のモチベーションが低下し、結果的にプール総数が縮小するリスクあり

■現在出ている提案、議論
・初心者向け対応、51%問題などに協力してもらえるpoolを公式から推奨してはどうか？
　初心者向けのドキュメントの設置、51%問題に対するアラートの表示などを行って頂く

・現状、赤字でやってる所ばかりなので、下手にかき回すと危険

・結局、各々独自でやっている状況が最も公平？

・LAさんだけは、アラート対応してもらいたい所

他にもありましたら是非～

**Comment by hitobb** [comment]
私個人の意見です、皆様のご意見を強要するつもりはございません。

---

私は公式プールの設置には反対の立場です。

過疎っている分野へのテコ入れであればともかく、
現在、市場原理がうまく働いている場所に、
公式の看板を持って乗り込んでいくメリットが一切見出せません。

Pool運用は皆様が想像している以上に負荷がかかります。
ただでさえ足りていないエンジニアの方々に、さらに負荷をかける行為は避けたいです。
（例えば、毎年の確定申告用に、すべてのマイナーに対する払出明細と時価を管理する必要があります）

Dev支払い用の収入源が目的であれば、別の活動に変更できないでしょうか？

**Comment by yenxrutile** [comment]
ありがとうございます。
今後も時々似たような議論が起こりそうなので、見かけた際は、こちらの経緯を紹介させて頂きます。
Dev向けの活動としてはNGの件、承知です。

**Comment by Aeinsk** [comment]
公式を名乗らずに開発支援を目的とした一般プールとして新しく建てサービス提供（Dev含め）してくれる人などへの寄付の財源にするのはどうでしょう
日本でいう独立行政法人みたいな

**Comment by hitobb** [comment]
寄付の財源が必要なことは理解しますが、それがマイニングプールである必要はないと、個人的には考えます。もっと他の必要とされているサービスがあれば、そちらの立ち上げに先行投資し、財源を確保したいです。

繰り返しますが、これは私個人の意見であり、Devの総意ではありません。

**Comment by zinntikumugai** [comment]
https://github.com/BitzenyCoreDevelopers/others/issues/13#issuecomment-371677767
で書いたので再コメントになりますが
1. 逆に集まる恐れがあるので51%問題が発生する恐れがある
1. 誰がどのように運営するのかが問題
1. 収益を目的にするとむしろ利用者が減る恐れもある
1. (私のような)個人でのりでやってるPool運営者のやる気低下

があります

私としては __誘導__ が一番双方にメリットがあると思います
[私が作ったPoolリスト](pool.bitzeny.pw) 程度の活動でも十分かと個人的には思います

**Comment by yenxrutile** [comment]
https://twitter.com/bitzenypoolbot/status/971943666716622848
↑こんな感じで集中警報＋人畜さんの[poolリスト](https://pool.bitzeny.pw/)をTwitter公式で流せるようにすると良さそうですね。

**Comment by hitobb** [comment]
**現時点では公式Twitterを利用する必要はない**と考えます。
監視BOTにて情報拡散できていますし、51％問題が発生した際にRTする程度で良いと思います。

Pool運用＆Pool監視ツールを作成して頂いている彼らを信じ、任せ、見守るべきではないでしょうか？

**Comment by yenxrutile** [comment]
了解致しました。
・現在稼働している個人の活動をCoreが上書きする事はしない。
・既存のサービスが停止し、ユーザー、ホルダーに不便が生じた場合、サポートを行う。
こんな感じの共通認識としましょうか。

**Comment by zinntikumugai** [comment]
個人的にはCoreは個人活動を応援+紹介ぐらいでとどめておくのがいいかな

あとは
```
マイニングする方へ
https://lab.ukkey3.space/BitZenyMiningPoolInformation.php
https://pool.bitzeny.pw/
https://github.com/kazu0617/BitZeny-Starter/wiki/Current-Pool-List
これらを参考にPoolの分散にご協力お願いします
#BitZeny
```
とかぐらいでもいいと思いますよ

**Comment by yenxrutile** [comment]
ありがとうございます。
こちらの要件、なげせんさんに取り次ぎ致します。
～～
・ukkeyさんにご連絡の上、程よい間隔でANNして頂く。

**Comment by hitobb** [comment]
**公式Twitterが新規テキストを作成し、Pool監視サイトを紹介する手法について、私は反対です。**

CoreDevチームをひとつの会社に例えると、Pool構築している方々や、Pool監視ツールを作成されている方々は別会社の扱いになります。どんなに社長同士が仲が良いとはいえ、他社の製品についてプレスリリース（＝新規作成したツイート）を出す行為は、違和感を感じざるを得ません。なお、他社のプレスを広める（＝RTする）のは、間にCoreDevチームの意図が紛れ込まないので、合理的な手法だと考えます。

他の方々のご意見も伺ってみたいです、いかがでしょう？

**Comment by yenxrutile** [comment]
ありがとうございます、私は異論ございません。
人畜さんのプランを折衷案と捉え、はやってしまった所がありました。
今後適切な判断が出来るよう、知識を高めて行きたいと思います。

**Comment by bellflower2015** [comment]
> 他の方々のご意見も伺ってみたいです、いかがでしょう？

ひとばしらさんの意見に賛成。
公式Twitterでの発言は当然、公式見解だと思われるし、「お墨付き」を与えてしまうことによって必ず不公平感が生じますので。
中立であるべきです。
コミュニティの活性化に貢献していると判断できるものは、積極的に「紹介」を行えばよいと思います。

**Comment by zinntikumugai** [comment]
@hitobb 
[私の作ったリスト](https://pool.bitzeny.pw/) は紹介を目的に(勝手に)作ってますが自分が良くても他のPoolの中では良いと思ってない方はいるかも知れませんね

この場合はそのサービス側のツイートをRTする感じでしょうか？

**Comment by Aeinsk** [comment]
公認非公認の問題でTwitterでの特定のプールへの反応はしない前提として.techにプール一覧を作成してそのリストに掲載するときに
・51％問題の対策をする
などの合意を得るのは難しいですか？

掲載には関係なくプールの稼働チェックされるのに賛成か反対か聞いておくなどできそうですが

**Comment by yenxrutile** [comment]
時々、指定期間中に自分のブログなどで作成して頂いた
51%問題の記事をツイートした人に、エアドロするイベントを
打つような施策はいかがでしょう？
過去に作成した記事でもOK。

**Comment by hitobb** [comment]
話の腰を折るつもりはないのですが、論点がブレて来ているように思えます。

本issueの議題は「公式プール設置の可否」です。
51％問題については別のissueを立てたほうが良いかと。
また、いったん結論が出たものについては、クローズも視野に入れて頂ければと考えます。
（必要に応じて、再オープンできます）

**Comment by yenxrutile** [comment]
承知致しました。

公式プールの設置の可否に関しては、概ね以下の要点を理由としまして、
現状では否と結論付け、本isshueをクローズ致します。

・プール運営に結構なリソースを取られてしまう

・現状の市場のバランスを崩してまで行うメリットが無い

・プール分散化の対応に関しては、既に個人活動がいくつも立ち上がっているので、
　公式で新規テキストを起こし、役割を奪うような事はしない。
　(※この点に関しては他の分野においても共通)

・余程切迫した際に、RTでアラート原文を拡散するのは適切な対応の認識

51%問題への対策に関しては、下記のisshueにて引き続きご相談出来ましたらと存じます。
以上、宜しくお願い致します。

51%問題への対策に関して
https://github.com/BitzenyCoreDevelopers/others/issues/17
