### ISSUE TITLE
Owner権限を持つアカウントについて

### ISSUE THREAD

**Issue by ghost** [BitzenyCoreDevelopers/others#16]
投稿時点では BitzenyCoreDevelopers のOwner権限を持つアカウントは @hitobb @BitzenyDevTeam の2アカウントに限られる。これらのアカウントが活動を停止した場合に BitzenyCoreDevelopers を管理することができなくなる。GitHub上での活動が活発であり、信用のおける（であろう）アカウントにOwner権限を付与されたし。なお @shirako-jp は捨てアカウントであるため不適切である。

**Comment by hitobb** [comment]
ご指摘頂いた問題点、ごもっともです。
Owner権限の付与作業について、調整を開始します。
まずは、適切と思われるメンバーについて、ここで議論できればと考えます。

私が強く推薦したいのは、以下のメンバーです。
cryptomamiya
manate
zinntikumugai

本人の希望を確認したいのは、以下のメンバーです。
onokatio
acid-chicken

いかがでしょうか？
他の方々のご意見をお待ちしております。

**Comment by ghost** [comment]
@cryptomamiya @manate-anagram @zinntikumugai @onokatio @acid-chicken ping

**Comment by acid-chicken** [comment]
私のようなもので力不足でなければ是非お願いします。

**Comment by onokatio** [comment]
自分は基本ものぐさなのでOwnerにあまりふさわしくないかと。

cryptomamiya
manate
zinntikumugai

のお3方に聞いてみて、断られてしまったのなら自分でもいいです。

**Comment by manate-anagram** [comment]
僕はリブートサイトのコーディングを行っている程度ですし、
Owner権限をいただくにはあまりにも恐れ多いです。

**Comment by zinntikumugai** [comment]
まともになにかした覚えないと思いますがいいんですかね？
そんな私でも構わなければ是非お願いします

**Comment by cryptomamiya** [comment]
目的は更新停止の回避といった、保守性の向上ですよね。何かあった時の予備としてなら登録していただいて問題ありません。

**Comment by onokatio** [comment]
ということで暫定 @zinntikumugai さんと @cryptomamiya さんと　@acid-chicken さんになったぽいですね。

特に異論ないならこのままクローズですかね。

**Comment by ghost** [comment]
@hitobb @BitzenyDevTeam 権限の付与が済み次第closeしてください

**Comment by hitobb** [comment]
以下3名の方にOwner権限を付与しました。
絵文字で良いので、お知らせ頂ければと思います。
@zinntikumugai 
@acid-chicken 
@cryptomamiya 
全メンバーの確認が取れ次第、本件、クローズします。

**Comment by hitobb** [comment]
全メンバーの確認が取れたので、クローズします。
