### ISSUE TITLE
GitHubのアイキャッチ画像の刷新[デザイン案件]

### ISSUE THREAD

**Issue by yenxrutile** [BitzenyCoreDevelopers/others#18]
https://github.com/BitzenyCoreDevelopers
↑のTOPに表示される画像のリニューアルを予定しております。
新ロゴを使った物を想定しております。

私的な意見になりますが、Core以外の人が参加出来る要件に関しては、積極的に有志の方に
お任せしたいと考えております。

・作りたい方を募り、先着5名程度にコンペして頂く
　(案件内容、運営コスト的にそこまで大規模にしたくない)

・採用報酬、参加賞を用意

・運営への寄付を併せて募集

以上、ご意見など頂けましたら幸いです。

**Comment by yenxrutile** [comment]
すみません、掲題があまり適切ではありませんでした。
リニューアルする、と言う事のみ確定していまして、誰にお願いするか、どう言ったフローで
やるかは、まだ白紙からの段階となります。

**Comment by bellflower2015** [comment]
これから決まる新ロゴをそのまま使えば良いのでは？

**Comment by yenxrutile** [comment]
https://twitter.com/noah_wd/status/970289160689926144
こんな風にロゴ以外の装飾を付けたり、はめ込む用途に合わせて加工する部分は、
結局別の労力なんですよね。
本採用のかたにそのまま相談してみましょうか。
賞金出てますし、快く受けてくれるかも。

**Comment by bellflower2015** [comment]
確かに別途作業は必要ですよね。
本採用となったらその人に相談、は自然な流れだと思うので、相談してみてもいいと思います。
諸々御協力いただけるならそれこそBounty案件ですね。

**Comment by yenxrutile** [comment]
ぐれんさん、今回はおめでとうございます。
もしこちらの件、いいぜ！やってやるよ！と言う感じでしたら、是非ご連絡くださいm(__)m

**Comment by hitobb** [comment]
新ロゴの対応についての中間報告です。
取り急ぎ、私から観測できている活動だけ公開します。
メインはコンテスト主催チームの方々にお任せしているので、見えていない部分もあるかも。

・CC0（シーシーゼロ）の申請中（専門家にお願いしています）
　https://creativecommons.jp/sciencecommons/aboutcc0/
・ぐれんさんから、AIデータは展開済、SVGデータを依頼中
・シンボルマーク以外の部分については、少し調整はいるかも
・コアにロゴ用のリポジトリを作成予定

**Comment by ohac** [comment]
専門でないので間違えているかもしれませんが、CC0の場合、BitZeny以外で使用されたりしないでしょうか。
詳しくは知らないですが、くまモンとか初音ミクのように何らかの制限が必要ではないでしょうかね。

**Comment by yenxrutile** [comment]
SVGアップされましたのでピックアップ致します。
常識的な範囲であれば適宜利用して頂いて良い状況でしょうか？
>hitobb - 今日 午前12時16分
新ロゴ元画像を保存するためのrepository作りました。
https://github.com/BitzenyCoreDevelopers/logo

**Comment by hitobb** [comment]
@yenxrutile 
画像利用ルールはCC0 1.0 Universal準拠です。
CC0 1.0の説明については、readme.mdにてリンクを紹介していますので、ご確認願います。

**Comment by hitobb** [comment]
@ohac 
ご意見、ありがとうございます。
コンテスト法務関係者からヒアリングした内容について、こちらに展開します。

---

①権利取得構成（誰かが権利を買い受けて運営するパターン）か②CC0構成（権利放棄していただくパターン）かについては、コンテスト法務関係者で何度か議論しましたが、②を採用した理由は、以下のとおりです。

１　既出のとおり、買い受けるカチッとした主体がないこと。まず、形式の問題として、Bitzenyコンテストは法人化されていないため、単純に買い受けるとすると、コンテスト運営者全員が著作権を共有するというかたちになります。これでは管理できないので、誰かが代表して買い受けるのが現実的ですが、一私人に帰属させるのはやはりリスクが大きいです。法人がない（それを新規に作る隙もない）以上、買い受けるというのは難しいという判断です。

２　また、買い受けるとなると税金の問題が無視できません。今回、寄付を集めてそれを優勝者の方にお渡しするという構成にしているわけですが、著作権を買い取るとなれば、税務署は、優勝者の方に送金される額は、その対価として支払われたとみるはずです。そうすると、Bitzenyをそこで使ったことになり、取得時との使用時の価格差がある場合は、価格税金が発生するのではないかという懸念があります。こちらは税理士さんマターですが、完全にクリアできるか不明でしたので、この点からも②の方が簡明で良いかなと判断した次第です。

３　権利を保有したとして、申請毎に許諾をする、あるいは、不適切な使用があった場合にそれを是正する人的・金的コストを負うべき人がいない（企業であればその一部問が対応しますが今回はそれがない）というのもあります。

以上の次第で、②を採用し、迅速な普及を目指すほうが良いのではないか、ということとなったものです。

---

**Comment by bellflower2015** [comment]
CC-BYではなくCC0に「せざるを得ない」という事ですか？
だとしたら、何がネックなのでしょうか？

素人目にNekoniumのやり方が上手いなと感じるのですが、あえてCC0なのが良くわかりません。
（わからないなら引っ込んでろと言われたら引っ込みます）
https://github.com/nekonium/nekonium.github.io/blob/master/resources.image/logo/README.md

**Comment by hitobb** [comment]
ご意見、ありがとうございます。
コンテスト法務関係者から再度、ヒアリングした内容について、こちらに展開します。

---

CC-BYでない理由は、誰かが条件をつける、でないほうが現実的でロゴマークの普及が進むと考えられるからです。
総合的にみてBitzenyの隆盛に寄与すると思いますし、この理由からコンテスト運営陣は選択したと私は認識しています。

---

※補足
法務関係者については、公平性を保つ為に外部の方にお願いしているようです。
よって、当事者ではなく、一歩引いたような回答になる点、ご理解願います。

**Comment by ohac** [comment]
@hitobb 
ありがとうございます。事情がだいぶ理解できました。
アイコンやキャラなどは中央が存在しないとなかなか難しいですね。
ちなみにBitcoinのアイコンの場合はソースコードと一緒のMITとなるのでしょうね。
FirefoxのロゴはDebianでは一時Iceweaselに置き換えたりしていて苦労されていたようですし。

**Comment by ghost** [comment]
https://en.bitcoin.it/wiki/Promotional_graphics

**Comment by hitobb** [comment]
現状報告。
新シンボルマークに合わせた「BitZeny」の文字デザインを依頼しております。
完成次第、アイキャッチ画像を差し替え予定です。

**Comment by hitobb** [comment]
アイキャッチ画像を作ってもらいました。
https://github.com/BitzenyCoreDevelopers/logo/tree/master/_icon
4月14日正午頃に、こちらの画像に差し替えたいですが、いかがでしょうか？

**Comment by hitobb** [comment]
五所川原さんから許可が下りましたので、アイキャッチ画像を差し替えました。
（反映に少し時間がかかるかもです）

https://github.com/BitzenyCoreDevelopers

**Comment by hitobb** [comment]
GitHubリンク先について、新画像が反映されていることが確認できましたので、クローズといたします。
