### ISSUE TITLE
orgドメインの交渉に関して

### ISSUE THREAD

**Issue by yenxrutile** [BitzenyCoreDevelopers/others#21]
五所川原さんタスクですが、返信待ちで2か月経過しています。
次段対応の検討、議論など出来ましたら幸いです。

**Comment by ghost** [comment]
・待てばお返事がいただけるのか
・お返事をいただけない問題が起こっているのか
・特に理由なく返事が来ないのか

時間がかかっている理由によるかと思いますので、まずは状況が把握できればと。

**Comment by hitobb** [comment]
五所川原さんに現状をヒアリングしてきました。

・2月末にTwitterのDMにてご相談。
・お返事をいただけない問題が発生中。
・本日の時点で、既読がついていないとの事。

以上となります。

**Comment by ghost** [comment]
なるほど、そうすると、内容証明と同じようなやり方をとるか、連絡を取ることを諦めるかですね。。
賛否あるとおもいますが、内容証明の代わりに公開質問という形をとるのはあるかもしれません。
いついつまでにお返事がない場合、も明記してです。

**Comment by nagasench** [comment]
6日前にメールを送っていますが返信がありません。

**Comment by ghost** [comment]
弱りましたね・・・・。

だれが主体となって実行するかというところは非常に難しいかもしれませんが、連絡が取れないこと自体で全体的な進捗が遅れて不利益という判断がされるのであれば、ドメインについては、ORGは非公式であるということを周知します、ということをお伝えするしかないかもしれません。

連絡をしたが返事がない、ということは、その連絡事項に関しての判断や責任を放棄しているという認識でいいと思います。（相手方からこちらに連絡して、という指定があったのであれば）
現状は「いつまでに回答を」という記載なしで連絡されたかもしれないのですが、一度そういう段取りを踏んでみても良いかもしれません。

**Comment by ghost** [comment]
思うんですが、バージョンアップしない人たち問題もアルゴリズム問題に対応することになった場合も、orgやbitcoinTalkの情報をきちんと更新できないことの影響が非常に大きいと思います。こういう問題が起こっていることを知っている人も少ないかと。
情報伝達における「公式」の役割は大きいので、最優先で取り組むべき課題ではないかなと考えます。

**Comment by nagasench** [comment]
再度メールやTwitterのDMで連絡を取ってみます。

**Comment by yenxrutile** [comment]
リアクション多かったので、こちらに残しておきます。
![nyamon](https://user-images.githubusercontent.com/36980340/37862370-042500c4-2f8f-11e8-8bb8-c1c5f354adb5.png)

**Comment by yenxrutile** [comment]
.tech移行に関して、共有出来ていなかったやり取りがありましたのでアップ致します。
![org1](https://user-images.githubusercontent.com/36980340/37942494-48e1a1a6-31ae-11e8-9263-3a9fb5f0aa27.png)

**Comment by hitobb** [comment]
なげせんさんが、メールチャックしていましたが、創始者さんからの返信は来てないそうです。

各方面に悪影響が出ていますし、そろそろ潮時かなぁ、、、

**Comment by nagasench** [comment]
毎日メールチャックはしてますが、いまだ返信は来ていません。
BTC240万くらい超えないと気付いてくれそうもないので.teckの方で動き出したいところです。

**Comment by ghost** [comment]
やってしまいましょう！
段取りとしては２パターンあるかなと思いまして、

１．公開質問的な流れを踏まえる
２．もう返事はないものとして、公式はtechですということの周知を進めてしまう

どちらにすべきかはどなたかが判断せざるを得ないかと。
私は１が良いかと考えます。

各ブログさんなどに対しては、地道ですがコメントなどでお知らせをして回るのがよさそうです。
これはボランティアを募っても良いかと思われます。

**Comment by hitobb** [comment]
Discord&Twitterでアンケートを希望します。

**Comment by ghost** [comment]
@hitobb 
いいですね！
結果を総意としての意味を持たせることもできますし、公開質問的な位置づけにもできます！

**Comment by bellflower2015** [comment]
@hitobb 
アンケートの設問文と選択肢の内容次第だと思うので、賛成／反対判断しかねますね。
「こういう前置きで、こういう選択肢で、2択で」など具体的なら、賛成／反対の検討できますけど…。

発案者とアンケ作成者が異なれば、伝言ゲームになって意味が無くなりそうでもある。

「○○日間、こちらがコンタクトを試みたものの連絡がないため、運営に実際に支障が出始めている。大変残念だが、コミュニティ版としての公式サイト、公式Twitterはコミュニティ側で新たに作成し、今後はそれらを公式扱いとさせてもらう」

みたいな感じで一方的に広報しても良い時期だとは思います。

**Comment by hitobb** [comment]
@daddypoco 
@bellflower2015 

言葉が足りていなかったようで申し訳ありません。

１．公開質問的な流れを踏まえる
２．もう返事はないものとして、公式はtechですということの周知を進めてしまう

daddypocoさんが示された、こちらの進め方について、どちらを選ぶかについて、だれか一人が判断するのではなく、アンケートを取って進めたいという主旨です。

**Comment by ghost** [comment]
趣旨理解しました！

**Comment by ghost** [comment]
上記アンケートのたたき台をつくってみました。
------
BitZeny公式サイトの変更に関するアンケート

【主旨】
　BitZenyの創始者氏との連絡が取れない状況となっており、氏しか管理ができない公式サイト「http://bitzeny.org/」を、現状の最新の情報に変更ができない状況となっている。
　先のサイトに記載されている情報は古いものであり、現開発陣の成果を公式サイトで発表することができていないため、いまだに古いソフトウェアが導入されてしまう原因となっており、今後の発展に良い影響を与えるものではない。
　これを解決するために、公式サイトを「https://bitzeny.tech/」に変更したい考えがある。

【アンケート内容】
　上記を実施するにあたり、どのような段取りを踏まえるべきかをアンケートにて決めたいと考えている。


方法１：
BitZeny創始者氏に対する公開質問を行ったうえで、その手続きをとる。

・BitZeny.orgの編集権限を現運営に移行してもらえないか
・移行してもらえない場合、BitZeny.techを公式とする声明を出すが良いか
・上記の回答を〇月〇日までにお願いしたい
・上記期限までに返事がない場合は、.techを新しい公式とすることを了承したと認識し、移行作業を進める

上記の質問はgithubのissueに記載するものとし、それに対するリンクをTwitterをはじめとした各種媒体に掲載する。
掲載する際には創始者氏への質問であることを明記する。
返事はgithubのissueにてしてもらう。


方法２：
もうお返事はいただけないものとして、.techへの移行を進める


みなさまに置かれましては、どちらの方法が望ましいかの投票をお願いいたします。

**Comment by hitobb** [comment]
方法１で期限4月末に1票します。

我々は3月末まで待ちましたし、+1ヶ月で反応が無いようであれば「回答意思無し」として進めてしまいましょう。

**Comment by sesameoil** [comment]
私も1に一票です
こちらの方が透明性が出て良いと思うからです

**Comment by ghost** [comment]
１のほうが手順としては段取り踏んでますし、1で行きましょうか。この方法であれば反対はないでしょう。
あとは、創始者氏への質問内容をまとめて、新しいissueとして建てましょう！

内容は、

> ・BitZeny.orgの編集権限を現運営に移行してもらえないか
> ・移行してもらえない場合、BitZeny.techを公式とする声明を出すが良いか
> ・上記の回答を〇月〇日までにお願いしたい
> ・上記期限までに返事がない場合は、.techを新しい公式とすることを了承したと認識し、移行作業を進める

これ以外に含めておくべきものはありますかね？

**Comment by ghost** [comment]
ANNに関しても新しいものをBCTに投稿する、というアイデアを白子さんが書いてたんで、
・回答なければ新しいANNをBCTへ投稿します
も追加できればと思いました。

**Comment by sesameoil** [comment]
Twitterアカウントを新アカウント移行するというのもどうでしょうか。
現状、Deckによる譲渡のため、新ロゴにプロフィール画像を更新できないそうです。
また、レイバンのサングラスを売り出したときにどうしようもなくなってしまう可能性もあります。

**Comment by ghost** [comment]
公開質問のたたき台です。

創始者氏へのお願い
・BitZeny.orgの編集権限を現運営に譲渡してください
・BCTの編集権限を現運営に譲渡してください
・Twitterについても、フルで運営できる権限を引き継いでください
・上記の回答を４月３０日いっぱいまでに、こちらのレスでお願いしたい
・個別にYes、Noでも構いませんが、Noの場合は理由を記載ください

回答がいただけなかった場合、回答が明確でない場合
・新運営として、BitZeny.techを公式とする声明を出させていただきます
・同様に新しいANNをBCTへ投稿します
・Twitterアカウントなどの公式運営を行うべきものも、新しく作成する場合があります
・これらの移行作業を進めさせていただきます
また、Yesという回答があったとしても、実行が伴わない場合は回答がないものとして進めさせていただきます。


BitZenyの未来を思えば時間の猶予はもうないので、各々の譲渡がNoであり、自ら再度指揮をとられるのであれば、それを明言ください

公開質問はこんな感じですかね？

**Comment by ghost** [comment]
ちょっと質問がございます。教えてください。

１．公開質問をするときに記載する相手方のお名前は何にしたらいいですか？（創始者氏じゃないきがしたので）
２．創始者氏のGitHubアカウント名お分かりになりますか？（それで回答してくださいと書きます）

あと、質問をかきましたら、皆さん目立つところに質問への誘導を書いていただければ！
連絡先がお分かりになる方は、一応連絡を入れていただければと思います。

あわせて、回答がいただけたとしてそれに対してのレスはそれぞれの担当の方にお願いしたい（さすがにそれは私は勝手に判断できない）のと、回答がなく期限が過ぎた後に関しては、私では動かせないのでみなさまどうぞよしなに！

**Comment by hitobb** [comment]
#32 にて、orgの引継ぎについて結論が出ましたので、クローズといたします。
