### ISSUE TITLE
TestNetのロゴについて

### ISSUE THREAD

**Issue by zinntikumugai** [BitzenyCoreDevelopers/others#23]
現在BitZenyコンテストでMainNetのロゴを投票で決めていますがTestNetの方をどうするか

現時点のもの
![TestNetlog](https://github.com/BitzenyCoreDevelopers/bitzeny/blob/z2.0.x/src/qt/res/icons/bitcoin_testnet.ico?raw=true)

**Comment by zinntikumugai** [comment]
1. 現状そのまま
1. 公式ロゴを加工したもの(グリーンぽく？)
1. 公式ロゴの作成者にTestNet用に改変していただく
1. 落選してしまったロゴのものから再選択
1. その他

一応TestNetだとわかりやすくなるようにしたほうが良いと思います
合わせてWallet上の各アイコンも変更していただけると利用者としてはMainNetとの区別がしやすいかな(2.0.0はMainNetと見分けがつきにくい)

**Comment by zinntikumugai** [comment]
使用場所ですが
- BitZeny TestNet Wallet
- BitZeny TestNet Discord

があると思います

**Comment by yenxrutile** [comment]
概ね要件まとまりましたので、TestNet用のロゴデザインを募集致します。

既に、ある程度方向性をヒアリングしており、要件が細かくなってしまうのですが、
もし我こそは！と言う方がおりましたら是非ご参加ください。

■募集要項
1.基本的なデザインは、MainNet版と同じでお願いします
　形状を変えてしまうと別のコインになってしまうため。

2.色は緑系でお願いします。
　色替えのみのサンプルで事前に希望を採った所、緑色が高い支持を得たので、引き継ぎたいです。
　※経緯を見たい方は、discordで"色パターンラフ案"で検索してみて下さい。

3.TestNetの表記必須でお願いします。
　"TN"、"TZ"などの文字をシンボル化してがっつり形状に組み込むような例は、1番に抵触する恐れがあります。
　基本になるロゴは、MainNet版と同じ形状だと認識出来る範疇のデザインでお願い致します。

4.グレースケールでもMainNetの方と見分けやすくして欲しいです。
　色覚異常対策として、グレースケール化した物でも、ぱっと見でMainNetと区別がつくようにして下さい。
　TestNetの文字の追加だけで無く、明度やグラデーションに違いがあると良いかもしれません。

5.【応募締め切り】 4/4 24:00頃(UTC15:00) (あまり大規模にやる予定が無いため)
　　募集終了後、discord内にて投票 4/7～4/8目途

6.元データは下記をご利用下さい。
　https://github.com/BitzenyCoreDevelopers/logo

7.応募用の画像は256x256程度あれば問題ありません。
　このissueにアップして行って下さい。

8.投票1位のデザインは、後日1024x1024のSVGの提出をお願いします。
　応募時点では、ベクターデータが無くても問題ありませんが、
　提出データと印象が変わらないような完成度でお願いします。

以上、宜しくお願い致します。
不明な点があれば随時ご相談下さい。

**Comment by LUPIN2** [comment]
TestNet用のロゴ２点
![1](https://user-images.githubusercontent.com/37474563/38014921-29ce4308-32a5-11e8-9c34-435ec35bd9ac.png)
![2](https://user-images.githubusercontent.com/37474563/38014922-29f97a46-32a5-11e8-8eef-c65dc4d12716.png)

**Comment by zinntikumugai** [comment]
@LUPIN2 
新testnetロゴのありがとうございます

@yenxrutile 
一つ提案なのですが(というか要望)
> 5.～
> 　　募集終了後、discord内にて投票 4/7～4/8目途

discord内の多分リアクションを利用した投票だと思いますが
discord内外の人の意見を取り入れたいのと、選択肢があると一番上や先頭を選びやすい傾向が結構あるので外部のサービス(or作成)をして選ぶのがいいかもしれません

また、`あまり大規模にやる予定が無いため`とありましたが、mainnetロゴ同様今後当分の間使われるロゴなので多くの人から選んだほうが納得がいく結果になると思います

**Comment by yenxrutile** [comment]
@じんさん
ありがとうございます。
もし良ければ投票システムの件、お願いする事は可能でしょうか？

私のリソース、知識で実現可能な範囲でと考えていました。
並びに関しては、投稿過程がオープンなので投稿順で十分フェアかなと。

コンペの規模に関しては、条件が既に結構具体的な事と、discordもフォーラムも
見ないのにTestNetに興味がある人がどれだけいるんだろう→いつの間にか決まっていても
不満を持つ人はそんなにいなさそう、と言う点などが主な理由です。

"応募してみたいけど、TestNetって何？"と言う人にアプローチするのは、
リソース的に無理があったため、現状としています。

私がこの部分やるから拡張しようぜ！と言った申し出であれば、是非ご相談させて下さい。

～～～～～～～～～～～～
ひとまず、募集期間の短縮や中断は起こらないかと思いますので、
デザイン応募に関しては、引き続き宜しくお願い致しますm(__)m

**Comment by yenxrutile** [comment]
すみません、私もいくつかアップしようと思っていたのですが、本業の方で死んでおり手が出せない状況です。。
4/4期限想定でしたが、数が全然増えなさそうなので、4月22日〆、月内決定くらいの尺にしましょうか。
リアクション、ご意見等頂けましたら幸いです。

**Comment by zinntikumugai** [comment]
@yenxrutile 
お久ですー
こちらとしては忙しいの一言なので伸ばしてもらえるだけでも助かります(ようやく回線入ったし(ち´；ω；｀)ぇ
ただ、BitZeny Core 3.x.x(予定)には乗り込みたいのでそこらへんも考えながらで(実際にいつっていうのが全く分からなけど

**Comment by yenxrutile** [comment]
ありがとうございます。
応募に関しては、一旦4/22まで延長させて下さい。

**Comment by hitobb** [comment]
テストネットロゴの応募数は現在、どのような感じでしょうか？

**Comment by yenxrutile** [comment]
現状、こちらに上がっている、るぱんさんの2点が全てになります。
私もいくつか提案させて頂こうと考えていたのですが、本業の方が、前に休日取れたのがいつだったかぐらいの勢いで、、
4/22の段階でいきなり応募が増える状況にもなり難いと思いますので、その時点で挙がってる物+さらに別のデザインが見たい(期限検討)、で一旦VOTEかなと考えています。
ひとまず、コミットされた物への支持の確認を挟んで次のタームに行きたいですね。

**Comment by yenxrutile** [comment]
![znyt_logo](https://user-images.githubusercontent.com/36980340/39083601-73974836-45a1-11e8-8e03-8addd66126c9.png)
![znyt_logo_gray](https://user-images.githubusercontent.com/36980340/39083603-75e0d04e-45a1-11e8-9d01-4f9b45b53f24.png)
相変わらず死んでますが、半休で1個だけ作ってみました。
mainの方とグラデを逆にしてます。

**Comment by bellflower2015** [comment]
素人がプロの作品を勝手にいじるのって、割と、作者と作品に対する冒涜のような気がするのですが、どうなんでしょうか。

**Comment by yenxrutile** [comment]
はい、そう言った考えもあるかと思います。
色変えだけにするとか、TestNetの文字を完全にロゴの外に配置する、とか具体案はありますか？

**Comment by kazu0617** [comment]
> 素人がプロの作品を勝手にいじると作者・作品に対しての冒涜となる   

となりますとTestNetも今回のように決めたうえで行う、もしくは今回のロゴ製作者の方に本来は募集要項になかったTestNet分も提出してもらう、といったことを強要しないといけなくなりますが…

**Comment by bellflower2015** [comment]
@yenxrutile @kazu0617 
意図が正確に伝わってなさそうなので追記しますが
一応クリエータ目線での意見と思ってください…
「えぇ…折角作ったのにこんな風に勝手に弄られちゃうの…」とか
「そこはめっちゃこだわったとこなのにめちゃくちゃ好きに弄られちゃってるなあ…」とか
作った側のこだわりってあると思うのですよね。
なので、
ベースとなるロゴがあるなら作者にまずお伺いを立てるのが筋なんじゃないかなーと思うです。
「何も気にせず好きに弄っちゃって！」と仰られたら好きに弄れば良いです。

**Comment by bellflower2015** [comment]
なので
@yenxrutile 「BitZenyロゴをベースとしてどう弄るか」という発想はまずいんじゃないか、という事を言っているつもりです。
@kazu0617 強要しなきゃいけない、なんて結論にはならないと思います。話を通してから弄ろうとしているのかどうなのか？てことです。

創始者様の件もそうですが、筋を通す、とか、リスペクトする、とかそういう話です。
すでに話を通した上での事なら、私の戯言は忘れてください。

**Comment by yenxrutile** [comment]
一応、general_jaでこねこねしてる最中に、ぐれんさんから直接リアクション頂いていますね。
顔文字だけだった気もしますが。

私的には、こちらの件、挙げた物を直接FIXとしなくても良く、既に出ているアイディアをステップにして、より良い物が提示されたり、支持を得た物に対して、さらに追加要望を取り込んだりして最終的な物になる流れでも良いと考えています。
自分が挙げた物も、これを採用してくれ！と言った感じよりかは、どこが良い、悪いと参考にしてもらい状況が前進すれば良いと言う気持ちが強いです。

と言った所をまとめているうちに、るぱんさんからも同じ内容のDMを頂きましたw
またご意見等ありましたら、取り込みつつ進めて行きたいと思いますので、よろしくです。

**Comment by yenxrutile** [comment]
![vote_180422](https://user-images.githubusercontent.com/36980340/39096380-38f2755e-468a-11e8-9e72-715f080dd87d.png)
それでは一旦〆ますね。
下記の内容で一回VOTEを取ろうと思うのですが、いかがでしょうか？

1.Aのアイコンが良い
2.Aのアイコンの方向性が良いが、さらに発展させた物を見てみたい
3.Bのアイコンが良い
4.Bのアイコンの方向性が良いが、さらに発展させた物を見てみたい
5.Cのアイコンが良い
6.Cのアイコンの方向性が良いが、さらに発展させた物を見てみたい
7.その他

複数投票OKで、上位3つくらいに絞れると良いかなと思います。
2,4,6,7に関しては、投票期間終了後にコメント頂きたいと思います。
(発展バージョンの作成に関しては、誰が行っても良い想定です)
ご意見等あれば、取り入れつつ展開を進めてまいります。

以前、じんさんに外部投票システムの件、相談しておりましたが、そこまでする状況では無いかなと思っているので、問題無ければ、discordにて対応致します。
以上、宜しくお願いいたします。

**Comment by zinntikumugai** [comment]
もう応募期間過ぎちまったのか...(といっても案がないけど

@yenxrutile 
上の3つに加えて現在決まってるBitZenyのロゴの色変え版(色はオリジナルTestnetロゴより)
も加えちゃってもいいんじゃないかな
あとやっぱり discord**だけ** になってしまうことも考えて外部でやることが一番かと
(discordでやると誰がどれだけやったのか判別がめんどくさい)

**Comment by yenxrutile** [comment]
>黄緑ver
はんぺんさんがUPしていた物ですね。
追加致します。

投票システムの件も了解です。
探してみますが、もし良い物があれば紹介して頂けると助かります。

**Comment by yenxrutile** [comment]
対応、週末になりそうです。すみません。

**Comment by yenxrutile** [comment]
![vote_180428](https://user-images.githubusercontent.com/36980340/39397803-05ea2a8e-4b40-11e8-98dc-4e65093c87de.png)
お待たせしました。
こちらで一旦アンケご協力お願い致します。
http://tasuketsu.com/top/vote?theme_id=NjIzNzIxNjgwNjA1NTIxMDI=
2票まで投票できるようにしました。
5/2 24時頃に一旦〆と致します。

**Comment by bellflower2015** [comment]
なんかダブルクリックしてしまったみたいで①に2票入ってますが、1票削っていただいてOKです。お手数お掛けします。

**Comment by zinntikumugai** [comment]
作ってるときには時遅しか...

@yenxrutile 
↑でやるなら告知したほうがいいんじゃないかな

**Comment by yenxrutile** [comment]
@じんさん
告知の方、対応しました。
投票システムの件は大変すみません、すり合わせ不足でご迷惑お掛けしてしまって。

**Comment by yenxrutile** [comment]
![znyt_vote4_1](https://user-images.githubusercontent.com/36980340/39592850-03f72efa-4f43-11e8-93a1-842cfc3aa77c.png)
遅くなってすみません。
また、告知、投票など多くのご協力を頂き誠にありがとうございました。

当アンケート開始時は、正直、"その他"がかなり伸びると考えていましたが、
想像に反して0票と言う結果になりました。
今回の結果を見る限りでは、現状の"A案"と、"B案の発展バージョン(複数可)"で最終決定に
持って行くのが良いように思います。

"B案の発展バージョンを見てみたい"に関しては、是非、アイディアのご提案、
可能であれば追加デザインのアップ等、引き続きご協力頂けますと幸いでございます。

WP作成トピックの方でご報告しましたが、今後こちらの活動に関しても私自身が手を
動かす事がかなり難しいので、取りまとめ等で可能な限りご助力出来たらと考えております。
状況的には、もうゴールが見えて来ていますので、大きな問題は生じないかと存じます。

今後とも、何卒宜しくお願い致します。

**Comment by hitobb** [comment]
@yenxrutile 手を動かすことが困難になった件、了解です。

本活動を引き継げる方、他にいらっしゃいますでしょうか？

**Comment by hitobb** [comment]
大変残念なのですが、こちらの活動、だれも引き継ぎ手がいないので、クローズといたします。
テストネットの新ロゴが必要な場合は、BitZeny Plus側で改めて検討したしますので、issue登録をお願いします。

https://github.com/bitzenyPlus/others

ご協力、ありがとうございました。
