### ISSUE TITLE
GPUMinerの登場と今後の対応

### ISSUE THREAD

**Issue by zinntikumugai** [BitzenyCoreDevelopers/others#24]
GPUMinerSource：https://askmona.org/9682

以前から掘ること自体はできたけどCPUMinerとの差がさほど大きくなくなったので今後どうするのか

BitZenyはBitCoinなどの専用機が必須な通貨に比べてCPUでも掘れますよがキャッチコピーなのでGPUで掘れやすくなったため薄れる恐れがあるかな

**Comment by zinntikumugai** [comment]
Discordでの案
1. アルゴリズムの変更(HF)
1. CPUMinerの最適化

**Comment by zinntikumugai** [comment]
私個人としては51%問題でLAPool以外で動かすこと前提ならある意味いい手かなと

**Comment by zinntikumugai** [comment]
HFにしても
- どのアルゴリズムにするか
- BitZenyを取り扱う取引所、Poolなどののアナウンス、変更作業など

時間と負担があるのでそこらも考えてくださいね

**Comment by cryptozeny** [comment]
もしHFをすれば、代案アルゴリズムがありますか?

**Comment by cryptozeny** [comment]
cpuminerのビルドオプションによってパフォーマンス違いです。 したがって、最適化が役立つと思います。

**Comment by ghost** [comment]
はじめまして、はるまきと申します。
この度の問題はHFが最適解だと思います
また、アルゴリズムはLyra2Zoinを提案します。
Lyra2Zoinはマサチューセッツ工科大学によって開発されたアルゴリズムで、GPU・ASICに極めて強い耐性を持っています。

**Comment by nagasench** [comment]
どうしてそう思うのですか？
ハショリ過ぎでしょｗ

**Comment by hitobb** [comment]
なげせんさん、悪気がないのは理解しておりますが、新規訪問者を煽らないでくださいwww

**Comment by cryptozeny** [comment]
lyra2zoinアルゴリズムについて勉強しようとしているのに、関連文書がありますか? 教えてくれたら探してみます。

**Comment by hitobb** [comment]
「現時点ではyescryptr8維持」が私の意見です。

採掘アルゴリズムの変更は、
プログラムの変更を行う為には、
以下の作業が必要になります。

・Coreプログラム開発
・cpuminerのプログラム開発
・全クライアントのバージョンアップ
・マイニングプールのプログラム変更（MPOS,NOMP）

4月のソフトフォーク、
5月前半のSegwit、
5月後半のBitZeny3.xを前に、
上記対応を全て行うのは現実問題として不可能です。

1月末から実施している
Ver2.0.xへのバージョンアップ促進活動も完了していない状態で
このようなHF対応を行うと、4月のソフトフォークすら失敗に終わりかねません。

―――

6月以降のロードマップについてを前提にであれば、ディスカッションを進めていきたいです。

**Comment by nagasench** [comment]
煽ってないですｗ情報が欲しいだけです。

**Comment by cryptozeny** [comment]
hitobbさんの意見に同意します。 6月以降ロードマップについて討論した方がよさそうです。

**Comment by sesameoil** [comment]
wを付けると煽っているように見えることがあります。
お気おつけを。

**Comment by hitobb** [comment]
大変失礼いたしました。

さて、6月以降のロードマップとしてHFするかどうかですが、
GPU採掘がどの程度ネットワークに影響を及ぼすか次第と考えます。

公平に判断できる基準として適切なものがありましたら、ご意見いただければ。
私が思いつくのは、以下です。

・今まで通り、特に問題なく使えている →現状維持
・Difficultyが1桁上がった　→HF必要
・ブロックチェーンの遅延やフォークが頻繁に起こる →HF必要

他にあれば、ご意見願います。

**Comment by nagasench** [comment]
了解しました。気を付けます。
はるまきさん申し訳ありませんでした。

**Comment by cryptozeny** [comment]
実験によるとgtx1070tiに約9 kH/s、消費電力約191wです。

https://i.imgur.com/BbU7qXB.png

**Comment by cryptozeny** [comment]
すみません、訂正します。 1080がなく、1070tiです。

**Comment by ghost** [comment]
私こそ知識不足ですみません。
こういう場ははじめてですが、普通に接して頂けると嬉しいです。
Lyra2Zoinですが、Lyra2Zoinを開発、運用しているZoinはBitZenyと同じく「万人が採掘でき、万人が利用可能な仮想通貨」を目的としているため、BitZenyとの親和性が高いと考えた次第です。また、先述の通り高い耐ASIC・GPU性能を持っているため、再三に渡るHFは不要と考えました。加えて、BitZenyの主な取引所のCryptoBridgeはZoinも扱っているため、対応がスムーズに行えると判断しました。

追記：参考資料
ZoinのGithub
https://github.com/zoin/zoin

**Comment by Harumaki-cryptocoin** [comment]
連投失礼します

Zoinのgithub
https://github.com/zoin/zoin

**Comment by hitobb** [comment]
なるほど、lyra2系 ( http://lyra-2.net/ ) のプロジェクトですね。
不勉強で申し訳ないのですが2017年後半に流行った「lyra2z」と同じものでしょうか？

**Comment by ghost** [comment]
いいえ、少し異なるようです。

**Comment by ghost** [comment]
僭越ながら今までの意見をまとめさせて頂きます

- **yescryptr8維持案**
・メリット
　・迅速に対応できる
　・新たな問題が発生しにくい
・デメリット
　・根本的な問題解決に至っていない（GPUで採掘できるまま）
　・difficultyの向上に伴い、新規の人や普通のPCで採掘できなくなる
　・BitZenyの特徴（誰でも掘れる、CPUで採掘できる）が無くなる可能性がある

- **ハードフォーク案**
・メリット
　・根本的な問題解決が可能
　・今まで通り、多くの人が使える
・デメリット
　・時間がかかる＆遅すぎたらプロジェクト存続の危機に陥る
　・新たなバグ潰しが大変
　・費用がかかる

以下、HF案の一例
- **yescryptパラメータ変更案**
・メリット
　・時間を掛けず素早く対応できる
・デメリット
　・根本的な問題の解決に至らない（いたちごっこの可能性が高くなる）
- **Lrya2Zoin導入案**
・メリット
　・確実にGPU採掘を長期に渡ってシャットアウトできる
・デメリット
　・新たな問題の発生が懸念される
- **ハイブリッド案**
yescryptr8のパラメータ変更をして、時間を稼いでる間にHFの準備を進める

**Comment by yenxrutile** [comment]
hfのデメリットは費用面もありますね。

**Comment by cryptozeny** [comment]
もしlyra、lyra2、lyra2z、lyra2zoinそれぞれどう違うのか説明してもらえますか? とても多くて難しいですね

**Comment by sesameoil** [comment]
yescryptのパラメータを調節するという手もありますね
メモリ使用量を更に増やすとか

**Comment by ghost** [comment]
@yenxrutile @Harumaki-cryptocoin 
> 費用がかかる

何の費用の話ですか?

**Comment by ghost** [comment]
https://askmona.org/9682#res_154
確かに時間稼ぎには十分使えますね！

**Comment by ghost** [comment]
@shirako-jp 確かに何の費用なんでしょう？

**Comment by yenxrutile** [comment]
@shirako-jp 新通貨のリブランディング、取引所のサポートなどです。

**Comment by ghost** [comment]
@yenxrutile そういう事なんですね。ありがとうございます

**Comment by nagasench** [comment]
思うのですが、GPUで掘る人がいなかった場合を考えていないのではないでしょうか？
difficultyやマイナー数の変化を見ておく必要があるようにおもいます。

**Comment by hitobb** [comment]
はるまきさん、とりまとめありがとうございます。
以下の点についてご意見をいただけますと助かります。

>yescryptr8維持案
>・デメリット
>　・本来の目的から逸脱する可能性がある

こちらのデメリットについて、
さらに詳しい説明をお願いいたします。
「本来の目的」とは何を意図しますか？

>ハードフォーク案
>・メリット
>　・根本的な問題解決が可能

「根本的な問題解決」についての説明をお願いいたします。
また「lyra2zoinの採用は確定していない」という点を前提に、
とりまとめ頂けますと助かります。

ハードフォーク後のアルゴリズムに対して
GPUマイニングが開発された場合、
yescryptR8と同じ問題にぶつかるかと思われます。
この点については、どのようにお考えでしょうか？

> yescryptパラメータ変更案

残念ながら、明確に、ハードフォーク扱いになります。

> その他

「lyra2z」は既にマルチプールが存在している為、
同一かどうかを確認させていただきました。

仮に「lyra2zoin」を採用したとしても、
マルチプールが構築された場合、
GPUマイニングと同等かそれ以上の影響を受けてしまいます。
とはいえ「lyra2zoinのマルチプールを作ることを禁止します」と
主張する権利は、私達は持っておりません。

この点については、どうお考えでしょうか？

**Comment by cryptozeny** [comment]
現実的に難しいことがあるが、最も良い方法はzoinがlyra2を改造してlyra2zoinを作ったように、我々も**lyra2zeny**のようなものを作ればどうですか?

**Comment by bellflower2015** [comment]
結局のところ、議論すべき本質は

「BitZeny」＝「GPU/FPGA/ASICマイニングを許さないコインである」
を明確に掲げるのか？

という話に集約されますよね？

仮にlyra2zoinが攻略される日が来た場合、
更にはその次に採用したアルゴリズムも攻略される日が来た場合、

やっぱりまたハードフォークを当然行うんだ！というポリシーにしてしまうのかどうか？

または、こういう時こそ、コミュニティ全体の意見を尊重するべきだ！という考えで行けば、
「絶対CPUだけじゃなきゃ困る！」
という人もいれば、ひょっとしたら
「GPUで掘れるようになるんなら、BitZeny持ちたい/買いたい/使いたい/広めたいかも」
という新規ユーザーも獲得できるかもしれません。

何を目指すかによって、根拠も結論も大きく変わりうると思いますが、その点は皆さんどうお考えでしょうか？

まさに「GPUMinerの登場と今後の対応」ですね。

**Comment by ghost** [comment]
@hitobb 
言い回しが不適切だったため、一部訂正させていただきました。

@bellflower2015 
確かにユーザーの意見をあまり汲めていないかもしれませんね…
私は1ユーザーとして、BitZenyのGPU採掘はあまり肯定的には捉えていません。
コストパフォーマンスに優れたGPUのマイナーが増加することで、difficultyが向上し、新規のマイニングユーザーが減少し、結果としてユーザーの減少が考えうるからです。
正直に申し上げますと、BitZenyの経済圏はまだまだ未発達です。もう少し経済圏の発展を待ってからGPU採掘について許可する方向性で良いのでは無いか…と思います。

**Comment by LUPIN2** [comment]
私はマイニングをしているユーザーです。技術的な事やHFの大変さを考慮してない意見です。
「BitZeny」＝「GPU/FPGA/ASICマイニングを許さないコインである」
事を望みます。
CPUマイニングに適している他の通貨は少ない＝技術や労力が大変。
他と差別化できる大きな魅力だと思っています。この魅力を捨てる事には反対です。
個人的に私がやりたいことはCPUマイニングが有利な通貨でしか実現しない。

**Comment by hitobb** [comment]
私個人の意見は、2.0開発トピックスに書いてあるように、
「yescrypt0.5(=yescryptR8)はBitZenyの心臓部だと考える」ので、現状維持です。
GPUであればより利益が得られるコインがあるので、
騒がれているほどマイナーは増えないのではないかと思っています。

https://bitzeny.info/d/39-z2-0-x

---ここから---
BitZenyの心臓部である、
yescrypt 0.5 の移植（0.5以外のバージョンへの変更NG）
---ここまで---

ただし、コミュニティ全体として
「BitZenyは常にアンチGPUであるべきだ」と合意が取れるのであれば、
6月以降、アルゴリズムの変更についてのアクションを起こします。

是非、皆様のご意見をお伝えください。

－－－

最後に蛇足です。

名誉名人さんが開発に成功したということは、
いつか誰かがどこかで同じ場所に到達すると同義です。

技術の進化を止めるわけにはいかないので、
現在公開されているマイナーを規制する云々のではなく、
次の一手を考える方向で動ければなと。

**Comment by shuichiro-makigaki** [comment]
BitZenyはCPUでも採掘が可能で、それはイカした特徴だと思います。なので、GPU採掘が公開されたらそれに対してアルゴリズム変えたりしたほうがいいんだろうなぁ、と思います。しかし「これは大問題で今すぐ気休めでも何か対策しないと!」という話ではないと思います。
「永年放置する気はないけれど……はてどうしたもんか、案をください」というくらいのスタンスでいいのではないかと……。

あと、「GPUでは採掘できない」「CPUでしか採掘できない」は偽で、「CPUでも採掘できる」が真です。GPUでは無理orCPUでしか無理orGPU廃絶、と表明するのは真実ではないので反対です。「CPU優位」というのも、語弊があるかなと……。CPUでもできるみんなの仮想通貨、という名目は賛成です。

以下長い理由

yescryptに限らずですが、近年のパスワードハッシュアルゴリズムは（安価になってきたGPUのような）超並列演算による総当たり攻撃に対して「既存のアルゴリズムで放置するよりは多少マシ」という意味において開発されています。ハッシュ関数は本来はパスワードの難読化のような目的のために作られているので、個々の計算自体は単純です（この計算が大変だと、パスワード認証自体が大変になっちゃう）。なので、単純な計算を並列に行えるGPUが基本的には優位で、CPUが優位になることはあまりないと思います。
耐性があるアルゴリズムとは言っても、GPUを増やしたりGPUの性能・機能が向上すれば、既存のCPUはたやすく負けます（原理的には）。しかし、GPUは高価+専用プログラミングが必要なので、「そこまでやるかどうか」の採算トレードオフによってGPUのハッシュレートは決まってくるのかと。そして、その開発熱量をBitZenyのyescryptに向けるかMonacoinのLyra2REv2に向けるかというと……今は後者の方がお得……。

**Comment by hitobb** [comment]
名無し名誉名人さんのマイナーが、KlausT-8.21-mod-r2にて、R16/R32対応しました。
流石ですね！
素直に称賛の拍手を贈ります！

http://askmona.org/9245

結果として、yescryptパラメータ変更案は意味が無くなりそうです。

**Comment by yenxrutile** [comment]
同じ話題が出てしまいそうなので、拾っておきます。
提案: BitZenyのコンセンサスアルゴリズム、PoW&PoIハイブリット化
https://twitter.com/onokatio_/status/976605127829172226

**Comment by onokatio** [comment]
ツイートが引用されていますが、それはほとんどネタで発言したものです。
ぼく個人的に言えば、BitZenyはそこまでCPUマイニングにこだわらなくてもいい（HF不要）と思うんですけど、どうなんですか。

**Comment by yenxrutile** [comment]
AlisやSteemit的な機能の議論
![z_sns](https://user-images.githubusercontent.com/36980340/37880889-4edeb8ee-30ca-11e8-8315-62005f798a1b.png)

**Comment by cryptozeny** [comment]
@yenxrutile どこで議論が進んでいますか?

**Comment by yenxrutile** [comment]
@cryptozeny 主にdiscordのgeneral_jaです。
https://discord.gg/xmWd3yy
ただ、いつもこの話題ばかりでは無いので、時々発生したものをGitHubに保管しています。

**Comment by hitobb** [comment]
AlisやSteemit的な機能の議論は、GPUマイニングと別の課題なので、個別に立てて欲しいです。

**Comment by hitobb** [comment]
ワタシの意見が変わっているので、改めてこちらで明記させてもらいます。

HFやむなし、です。
Discordアンケートの結果を鑑みてArgon2d採用に同意。
Argon2dが掘れるminerは存在しているので、その点については楽観しています。

各取引所と各マイニングプール運営の方々が同意していただけるのかが、非常に疑問。
一部取引所が強くANNやorgの更新を求めているので、こちらの問題も早々に決着をつけたい。

私的なスケジュール感として、アルゴ変更なしで3.0出して(BTC0.16追随と新ロゴの案定版)、その次のアクションでHFかなと。冒険する前に安全な地点でのセーブしておきたい。
また、blockheader変更やるなら、3.0テストネットで先行実験いかがでしょう？

**Comment by cryptozeny** [comment]
argon2dとlyra2z330(lyra2zoin)この二つが話が出たようです。 argon2dの方に実験をすることになりますか?

**Comment by Nanashi-Meiyo-Meijin** [comment]
lyra2z330のGPU掘りを作ってみたが、CPU掘りと同じくらいの速度になりそう。
ただ、lyra2z330は変な挙動をするコードがある。
int64_t nRows=330;
int64_t row=0;
int64_t step=-1;
この状態から、
row=(row+step)%nRows;
は正しく出力されているのだろうか？
たぶん、329が出力されるべきなんだろうけど、実際に出力されるのが15なんだ…
(0-1)%330=0xFFFFFFFFFFFFFFFF%330=15
これが正常だと言うならいいんだけど。

**Comment by hitobb** [comment]
@Nanashi-Meiyo-Meijin 

お礼が大変遅くなりました。
lyra2z330の件、わざわざテストまでして頂き、ありがとうございます。
とても参考になります。

現在、様々なアルゴリズムで実測値等々を拾い集めて、方式を探っている段階です。
argon2dは激重で運用に耐えられそうにありませんでした。
しばらく試行錯誤が続きそうな感じになってきています。
（なんだかんだでyescryptが一番バランスが取れていたというオチになりそう）

**Comment by onokatio** [comment]
なるほど、Discordとこっちで同時並行に話が進んでるからややこしいのか。

**Comment by hitobb** [comment]
現時点では、以下となります。

- マイニングアルゴリズム変更の実施時期は未決定
- マイニングアルゴリズムの選定も未決定（候補がすべてyescrypt 0.5に劣っていた為）
- もしアルゴリズム変更が行われる場合は「BitZeny Plus」のみが対象
- アルゴリズム変更が行われた時点で初めて「bitzeny」「BitZeny Plus」のチェーンが分岐

本議題がいつ復活しても良いようにBTC 0.16ベースの「BitZeny Plus」を進めます。

**Comment by hitobb** [comment]
開発はBitZenyPlusに引き継がれました。
こちらの対策につきましても、BitZeny Plus側にて検討を進めます。

https://github.com/bitzenyPlus/others

ディスカッション、ありがとうございました。
