### ISSUE TITLE
AlisやSteemit的な機能付与の議論

### ISSUE THREAD

**Issue by yenxrutile** [BitzenyCoreDevelopers/others#26]
一つのアイディア例として保管致します。
議論の進展により一旦結論が出て、もし全然違う機能の話に遷移するようでしたら
こちらはクローズして頂き別isshueとして下さい。
![sns_z](https://user-images.githubusercontent.com/36980340/37884007-d1ef5c8e-30e8-11e8-847f-aa541e5e5ec1.png)

**Comment by hitobb** [comment]
本機能がないことによって、BitZenyのメインチェーンに大きな影響が出るわけではないので、オープン状態を維持する必要はないのではと考えます。
（エンハンスについての意見を拾い上げるという視点では、issueを立てた意味はあります）

是非を含めて議論の進展がなさそうなので、いったんクローズ。
話題が再燃したら、再オープンでいかがでしょう？

**Comment by yenxrutile** [comment]
承知致しました。また格納すべき意見が出て来ましたら再開致します。
