### ISSUE TITLE
BitZeny版Counterpartyの動向

### ISSUE THREAD

**Issue by yenxrutile** [BitzenyCoreDevelopers/others#27]
時々話題に出るので、現状把握のため情報共有にご利用下さい。
こちらのisshueに関しては、活動可能or不能の結論が出るまでで良さそうでしょうか。

■関連
BitZeny版Counterpartyを作るプロジェクト
https://bitzeny.info/d/34-bitzeny-counterparty/22

**Comment by yenxrutile** [comment]
daddyさん情報ありがとうございます。
![znip](https://user-images.githubusercontent.com/36980340/37899850-913f9156-3127-11e8-868a-f16b914b6edc.png)

**Comment by ghost** [comment]
すみませんこちらに書けばよかったですね。
新しい情報が得られたらこちらに追記するようにします。
結構センシティブな情報になる可能性があるので、その場合はまずコアの方々にお伝えします。

**Comment by hitobb** [comment]
本issueが公開されたきっかけの会話を共有します。

![1](https://user-images.githubusercontent.com/14948578/37900540-727b0500-3129-11e8-93b6-8655197e3251.png)

**Comment by hitobb** [comment]
活動可能or不能の結論は出ているので、いったんクローズしますね。
