### ISSUE TITLE
CoreDev用のTwitterアカウントの運用について

### ISSUE THREAD

**Issue by kazu0617** [BitzenyCoreDevelopers/others#29]
以前（1月頃）bitzenyの公式アカウントについて話題になった際に、BitZenyCoreDev用のアカウントがいるかもしれない、といった話がありましたのでそのタイミングに取得したアカウントがあります。
それに関して先日再度Nagesen氏から提案があり、yen_rutile氏から賛同がありましたので、運用について意見をすり合わせれればと思いIssueを立てた次第です(共同で運用する、しないも含めてすり合わせれるといいかなとは思っております)。
![image](https://user-images.githubusercontent.com/6259214/38045287-56a6e90a-32f7-11e8-99b6-f52f094a1af1.png)

**Comment by nagasench** [comment]
長い間放置する事になってしまい申し訳ありませんでした。当時の状況からも大分変化がありますし、CoreDev用のアカウントも必要になってくる状況になってきたかなと感じます。
アカウントの運用について再度話し合えたらと思いますが如何でしょうか？

**Comment by kazu0617** [comment]
了解です、自分としましてはいつでもOKですが、Discord上である程度決めた上で決定事項を書く方向でいかがでしょうか

**Comment by kazu0617** [comment]
このTwitterアカウントについてですが、#30 での名称が決まり次第追従して
名称変更を行う予定です。特に反対がなければ 👍 をつけていただけると幸いです。
逆に、反対意見等あれば 👎 や代替意見の方よろしくお願いします。

**Comment by hitobb** [comment]
BitZeny Plusに関する「かわら版」置き場を作りました。
以降の議論はこちらでできればと考えます。

お手数をおかけしますが、こちらに再投稿を頂けないでしょうか？

https://github.com/bitzenyPlus/others

以上、ご検討よろしくお願いいたします。

**Comment by yenxrutile** [comment]
https://github.com/bitzenyPlus/others/issues/3
plus版に引き継ぎ致しました。

**Comment by kazu0617** [comment]
Plusのほうに移行する関係で、こちらのIssueはクローズとさせていただきます。
