### ISSUE TITLE
GitHubのアイキャッチ画像はこのまま？

### ISSUE THREAD

**Issue by yenxrutile** [BitzenyCoreDevelopers/others#3]
・あまり拘らないのでどちらでも
・新ロゴ決定後にリニューアルしてはどうか

**Comment by onokatio** [comment]
リニューアルする予定です！たしか。

**Comment by yenxrutile** [comment]
情報ありがとうございます。
リニューアル完了でクローズ致します。
※3/6 訂正
bitzeny_wikiへの記載が完了しましたら、クローズ致します。

**Comment by hitobb** [comment]
ロゴコンテストが終わり次第、検討を再開したいですね。

■個人の希望
ロゴコンテスト１位のロゴにしたいです。

**Comment by yenxrutile** [comment]
ありがとうございます。
こちらに関しましては、解決した物としましてクローズさせて頂きます。
引き続き、別のisshueにて内容を煮詰めて参ります。
