### ISSUE TITLE
「BitzenyCoreDevelopers」文字数が多すぎる問題

### ISSUE THREAD

**Issue by hitobb** [BitzenyCoreDevelopers/others#30]
現在のOrganizationsを公式に昇格させるにあたり、「BitzenyCoreDevelopers」は文字数が多すぎるので、リネームしませんかという提案です。

**現状整理**
- bitzeny個人アカウントは創始者さん
- BitzenyDevTeam個人アカウントは五所川原さん
- BitzenyCoreDevelopersを作成してくださったのは五所川原さん
- 当時は分かり易さ重視だったので、文字の長さまで考えていなかった

**Organizations名の候補（案）**
- BitZenyCore
- ZenyCoreDev
- ZNYCoreDev
- BitzenyDevTeam
- bitzeny

そのほか、ご意見があればぜひ。

**Comment by bellflower2015** [comment]
`BitZenyCore`もいいけど、これだとチーム名なのかプロダクト名なのか解りにくく紛らわしい。ので、

`BitZenyDevTeam`に一票！

**Comment by kazu0617** [comment]
使われないと思いますが、Keybaseの方にてBitZenyCoreDevelopersでは長すぎ、登録できませんでしたのでそのタイミングにはBitZenyCoreにさせてもらいました。変更可能なので参考になるかは微妙ですが、一応。

**Comment by ghost** [comment]
@hitobb bitzenyは既に使用されています
https://github.com/bitzeny

**Comment by hitobb** [comment]
@shirako-jp

ご指摘ありがとうございます。
githubのURLは、個人に紐づくアカウントか、Organizationsとしてのアカウントかの区別はないのですね。
そうであれば使えませんね、勉強になりました。

**Comment by Lesmiscore** [comment]
BitZenyDevsなんて名前ならカッコいいなーなんて思いました

**Comment by hitobb** [comment]
新名称が決まったので、こちらの議論も再開します。

**Comment by hitobb** [comment]
■既に使われていて、使えないもの
bitzeny
BitzenyDevTeam

**Comment by hitobb** [comment]
個人意見

「BitZenyDevs」あるいは「BitZenyCoreTeam」にしたい。

**Comment by kazu0617** [comment]
BitZenyDevsを支持します

**Comment by hitobb** [comment]
短いほうが良いので「BitZenyDev」(sをはずす)のはいかが？

さらに短くするなら「zenydev」ですけど、zeny商標問題があるので避けたい。

**Comment by hitobb** [comment]
通称で定着している「BitZenyCoreDev」(コアデブ)もありですね。

みなさま、いかがでしょう？

**Comment by cryptozeny** [comment]
plusに名前を変更したので、`BitZenyPlus`にしたらどうですか?

**Comment by balloonfc-hub-git** [comment]
新名称を活用することはできますでしょうか？
旧名称と別れたことを考えると、Plusをいれるようにした方がいいと思います。

BitZenyPlusDev、長ければBZPDevとかいかがでしょうか。

**Comment by doisatoshi** [comment]
BitZenyDevに一票

**Comment by bellflower2015** [comment]
ZNYDevまたはznydevで。一番短い。

**Comment by Tanisun** [comment]
BitZenyDevs

がいい感じに思えます❗😃

**Comment by yenxrutile** [comment]
旧BitZeny、及び今後もしBitZenyPlusとは別のHFが出来た場合においても、全てのDevを包括するのでしょうか？
Plusのみが対象になるのでしたら、名称にPlusを含めた方が良さそうですね。

**Comment by hitobb** [comment]
難しい問題ですね。

私自身は今後、bitzeny 2.0.1系のみしか支持する予定はありません。別のHFが発生したとしても、手を動かすことはないでしょう。

とはいえ、他の方がbitzenyをフォークすることを止める予定もありません。

新しいorganizationを立ち上げたほうが良いかもしれませんね。

**Comment by AkashiRiot** [comment]
他の方の案に乗っかる形ですが、新しくという方向でしたら「BitZenyPlusDev」がいいような気がしています。（何となくでナマいってごめんなさい💀）
現行：BitzenyCoreDevelopers(21桁)
提案：BitZenyPlusDev（14桁）
（この名称については実際に手を動かしてきた方の声に重きを置く方でスパーンときめちゃってもよい気がします）

**Comment by hitobb** [comment]
とある方から、コメント貰っていました。
こちらに投稿してくれないかもしれないので、代筆です。

【リネーム絶対反対】
2017年半ばから約1年間「BitzenyCoreDevelopers」の名前で活動してきました。
現時点でorganizationをリネームすると、1年間蓄積したリンク情報が無効化してしまいます。
過去のナレッジを自ら放棄する行為なので、同意できません。
ｰｰｰ

私個人としては完全に説得されたので、リネームなしかなぁと思い直しています。
皆様、いかがでしょう？

**Comment by cryptozeny** [comment]
@hitobb

一理ある意見です。 同意します。

**Comment by kaminuma** [comment]
それで構いません。

**Comment by bellflower2015** [comment]
リネームするなら、HFでGitHub移る（bitzenyPlus）ときでいいんじゃないですかね。
こちらの組織名はそのままでも良いでしょう。

**Comment by hitobb** [comment]
ご意見ありがとうございます。
それでは

# こちらの組織名はリネームしない

という結論で、本件クローズします。
