### ISSUE TITLE
 HF宣言の可否、新コイン名称

### ISSUE THREAD

**Issue by hitobb** [BitzenyCoreDevelopers/others#34]
# 背景

「#32 BitZeny初代開発者 orphanate氏 へのお願い」
こちらの結果を踏まえてのアクションとなります。

BitZeny.orgの更新が現実的に難しくなりました。

BitZeny 1.x ブロックチェーンと、現BitZeny 2.x以降のブロックチェーン混在を避けるために、Hard Fork宣言、および、現BitZeny 2.x以降ブロックチェーンのリネームを検討します。

# アンケート 1

Hard Fork宣言について、以下のいづれを支持するかをコメントください。

- 賛成
- 反対
- その他

# アンケート 2

結果としてHard Forkする場合、新コイン名称を募集します。

また、募集方法についてもアイデアがあれば、別途、コメントを頂けると助かります。
（例：Twitterで公募する、新名称の決定に関するコンテストを行う、など）

**Comment by bellflower2015** [comment]
反対

改名＋HFだと今使ってる取引所に全部拒否される可能性がある
「名前を変えない」というメリットはそこにある
（取引所に正統な後継と思ってもらうには必要なんじゃないか）

HF宣言というよりも、1.x以前はもう古いから推奨しない　と言えば良いだけ。

名前を変えると、後継と思ってもらえる取引所と、名前違うからダメと言われる取引所と分かれてしまって
1.x問題も絡んでより事態が複雑になり混乱するおそれがある

完全に別コインとして進もう、取引所にも新たに上場fee払ってやり直そう、というなら話は別だけど、
新たにスタートして認知してもらうのめちゃめちゃ大変だと思う

反対なので2の回答は無し

**Comment by hitobb** [comment]
私の個人としての意見を。

- アンケート1

その他：皆様の判断に委ねます。

- アンケート2

「BitZeny SegWit」

BitZeny 1.xのチェーンと分岐する理由をストレートに表現。
（なお、ネームセンスがないことは自覚しております）

他の方もぜひ、ご意見ください。

**Comment by hitobb** [comment]
ワタシは今回、皆さんの意見を尊重します。
アトミックスワップが成功したので、私がやりたかったものは出来ました。
これをBitZenyの名前で継続するか、別コインにするのかは、皆さんに任せます。
なお、私は今後、アトミックスワップが成功したコイン側についていきます。

**Comment by yenxrutile** [comment]
![harumaki1](https://user-images.githubusercontent.com/36980340/39469731-b01eb570-4d74-11e8-8c43-300f494560fd.png)
同じ意見が重複しそうなので、その他としてピックアップさせて頂きます。
こちら取引所の仕様的に不可となるそうです。
HF側の追加上場必須。

**Comment by bellflower2015** [comment]
@yenxrutile 
どの取引所ですか？
割とHFでウォレット更新してもらってるコイン見かけますが…
そういうとこは追加費用払ってるってことですか？

**Comment by yenxrutile** [comment]
元のコインそのままでHFを追加上場なら無料でやってくれる所は多いと思いますが、
元のコインの名前、アイコン、ウォレットを無料で総とっかえしてくれるのは、余程の新興とか
再登録費用が気にならない(実は少し費用が掛かっている)ような取引所じゃないでしょうか。
すみません、私も2次～ソースなので、各取引所毎の規約までは調査しておらずで。

**Comment by bellflower2015** [comment]
@yenxrutile 
それなら納得です
私が反対票に投じたのは、まさにこれまでのそういった費用が全て無駄になってしまうからです

**Comment by kazu0617** [comment]
個人的に気になっているのは、HFする際にはそこの取引所に上場した人がどっちのコインのことを考えて上場していたか、ってのを説明すれば通りそうな気もしなくもなさそうですが、前例がないので何とも言えなさそうですね…

自分もあえてどちら側に票を投じるというわけではなく、皆さんの意向に任せる方向で。HFすることになった場合は今のチェーン（2.x~のチェーン）に追従します

アンケート２の名称については、いいのが思いつかないのでひとまず出しません…
アンケートに関してですが、Discordで投票専用のチャンネルを作り、そこにスタンプを押す形での決定を提案します（いわゆる、Sproutsがアイコンを決めるときに使用した手法です）。

**Comment by hitobb** [comment]
取引所の上場ですが、実際のところは交渉次第です。
0/1判定で絶対ダメですというような、硬いルールはありません。

これまでの経験からですと、ZNY上場時に費用負担したアカウントからの相談であれば、臨機応変に対応していただけます。もちろん、追加費用を要求してくる取引所もあるかとは思います。

**Comment by ghost** [comment]
現時点では、BitZeny 2.0.1はorphanate氏のBitZeny 1.1.0と**まだ**互換性があります。
もしPoWのアルゴリズム等を変更するなりしてその互換性が失われた場合、今後もBitZenyと名乗り続けるのは混乱を招く要因となり得るのではないでしょうか。

何も知らない外部の人からしてみれば、名前を変えたほうが分かりやすいでしょうね。別物だと。
取引所は交渉次第でしょうから、今のうちからHF後のそれに追随可能かどうか質問を投げ始めますか？

**Comment by Aeinsk** [comment]
HFを初代開発者からの独立と考えているので賛成ですが
これまで上場にかかった費用、新アイコン等の制定の過程が無駄となってしまわないか心配です。
また可能であるならば早いうちからHFを考えているからそれにかかる手続き、費用などを問い合わせておくと今後の判断の参考になるかと思いました。

**Comment by cryptomamiya** [comment]
ツイートの内容こちらにも書くね。
賛成

bitzenyのウリはみんなが参加できること。

最新OS（ubuntu18.04）の対応や少し高額な機器（GPU）によるマイニングへの対策を打ち出していき、アイデンティティを維持する。その為にHFが必要な話ならば、私はHFを支持します。

生みの苦しみはありますが、乗り越えないといけない時かと思う。

**Comment by yenxrutile** [comment]
・アンケート1
賛成

HF無しに今以上の技術追求、サンドボックスとしての発展拡大は難しいと思いますので。

・アンケート2
BitZeny Light
軽い、明るい、right=正しい、あたりから。
極力、今のロゴ等がまるっと使えなくなるような名称は避けたいですね。。

・募集方法
告知は広くやって、新規項目の追加と、既出の項目にfav付けるのをどちらも出来る投票システムで受け入れするのが良いかもしれませんね。
2chのまとめサイト等でコメント欄にプラスマイナス付けられるようになってる物がありますが、同じような感じ。

**Comment by cryptozeny** [comment]
少しだけ待ってみれば、オリジナル開発者の返事を受けることができないでしょうか?

オリジナル開発者が海外にあるとか、事情があり得るために、約15日程度だけ決定を保留したらどうかと思います。

**Comment by yenxrutile** [comment]
@cryptozeny
その調子で4ヵ月、音信不通が続いていますので。。
送金詰まりも拡大している今、対策や判断に関して頼るべきは現開発じゃないでしょうか。
対立的なHFと言うわけでも無いですし。十分な手順を踏んでいると思います。

**Comment by LUPIN2** [comment]
アンケート1
賛成です。
旧公式に古いwalletや情報が掲載され続けるため混乱するので。
ちらっと今wiki見てみましたが、リンク先のブログの記事にも旧公式からWALLETをダウンロードするよう記載されリンクされていますね。
旧公式が更新できないので賛成。

アンケート2

募集方法
投票で決める際には、複数候補の中から上位2点程度を投票で選んだ後に最終的な投票で選ぶようにしたほうが良い気がしてます。私が結果が下位の物に投票した後、１位の物より２位の方がいいなって事があったため。

**Comment by satetsu888** [comment]
・アンケート 1
(1.xと2.xの識別のためのHFには)反対
GPU対策としてアルゴリズム変更はまた別の問題だと認識しているのでここではノーコメント

#32 は言外の大前提として、

新運営として、BitZeny.tech を **(BitZenyの)** 公式とする声明を出させていただきます

という意味が含まれているものだと思っていました。
BitZenyの正式なバージョンアップとしての2.xを作ったわけではなく、BitZenyからフォークした別の名称の別のコインとしての2.xであったなら、最初から初代開発者にお伺いを立てるまでもなくやりたい人が勝手にフォークする自由は認められていると思います。
2.x をBitZenyとしてバージョンアップしたかったから #32 があったのだと認識していたんですが違うんでしょうか？

1.xと2.xの情報錯綜については、公式としての2.x対応の呼びかけと非対応の取引所やプールを新公式ページから外していくなどの情報整理と、新公式ページへリンクを集めて旧公式ページより検索結果に出やすくするなどを進めるのが正道だと思います。

**Comment by ghost** [comment]
@satetsu888 
> 2.x をBitZenyとしてバージョンアップしたかったから #32 があったのだと認識していたんですが違うんでしょうか？

#32 を実現できれば、コミュニティ開発によるBitZeny 1.2.xやBitZeny 2.xをBitZeny 1.1.0の正式な後継としてリリースしていたことでしょう。それが失敗した今、ANNやbitzeny.orgを理由にロゴの変更やウォレットの更新を拒否した取引所等の外部サービスは、新規でANNを投稿しBitZenyの後継だと主張したところでそれを受け入れないのでは?

そういった不都合が生じていなければ #32 は存在しません。
受け入れないところを切り捨てれば良いという意見もありますが、BitZenyが複数存在することは好ましくないと思います。

**Comment by satetsu888** [comment]
ちょっと書き込みが止まった気がするので僭越ながら挙がった論点についてまとめてみます。
僕の認識違いなどあるかと思うので変な箇所はツッコミをお願いします。

#### 1. HFした場合の各取引所の対応にかかる金銭的・時間的コストについて
- ZNY上場時に費用負担したアカウントからの相談であれば、臨機応変に対応してもらえると見込まれる https://github.com/BitzenyCoreDevelopers/others/issues/34#issuecomment-385658597
- 今のうちからHF後のそれに追随可能かどうか質問を投げ始めるべき？ https://github.com/BitzenyCoreDevelopers/others/issues/34#issuecomment-385667699

#### 2. GPU対策としてのHFについて
- 誰でも手持ちのPCでマイニングに参加できるアイデンティティ維持のためのHFをすべき https://github.com/BitzenyCoreDevelopers/others/issues/34#issuecomment-385677654
  - （個人的意見: #24 の話題にも思えますが、どうせHFが必要になるなら同時にやっちゃう？という視点があるのであればこのタイミングで一緒に話をしても良さそうに思います）


#### 3. ここから期日を延期して創始者の帰還を待つことはあるか？

- もう十分待った
- 2.x によるソフトフォーク(とそれによる1.xの送金詰まり）もはじまっておりこれ以上待たずに結論を出すべき https://github.com/BitzenyCoreDevelopers/others/issues/34#issuecomment-385878198

#### 4. 旧公式が更新できない問題について
- BitZenyが複数存在するのは混乱の元になるため、HF及び名称変更をすべき https://github.com/BitzenyCoreDevelopers/others/issues/34#issuecomment-385881524
- 旧公式は放置したままで情報の整理と周知、検索エンジン対策などで新公式が目立つようにすべき https://github.com/BitzenyCoreDevelopers/others/issues/34#issuecomment-385960539
- 旧公式が存在することで新公式をBitZenyのものと認めてもらえない不都合があるため、HF及び名称変更すべき https://github.com/BitzenyCoreDevelopers/others/issues/34#issuecomment-386020949

**Comment by satetsu888** [comment]
まとめた上でここからは個人的意見です。

> 4. 旧公式が更新できない問題について

旧公式が存在することは、混乱の元になる問題と取引所等で新サイトを公式として取り扱ってくれない問題の2つがあると認識しています。
HFと名称変更で後者の問題は解決すると思いますが、変更した名称が BitZeny XXX(Xは任意の文字列) みたいな感じだと前者の問題は変わらずに存在し続けて、結局BitZenyが複数ある状態になるのではという懸念があります。

懸念される具体例はこんなイメージです
- 新しいBitZeny XXXをマイニングしたくて [bitzeny XXX miner] などで検索
- 古いBitZenyのマイニングのページがヒット
- 検索者はBitZenyとBitZeny XXX の違いを知らないのでそのまま迷い込む

公式サイト以外にもマイニングや取引の方法など解説している古いページは多数存在していて、BitZeny XXXのユーザが事あるごとにBitZenyのページに迷い込んでしまう問題は当面発生すると思います。
これを解決に向かわせる最短経路は、新しいものも **BitZeny** として同じ名前で新しい情報を発信し続けることかなと考えています。

新しい名称がBitZenyと全然違うものになるならこの心配はないんですが、今のところはそういう方向の意見は見当たらないようです。

**Comment by yosio831** [comment]
**アンケート 1**
HF反対。
(ソフトフォーク/もしくは新をbitzeny・旧をbitzeny classicにする←取引所が許すならこれに一票)

理由はいくつか。
【モナコインやリップルで同じことがあったら嫌だ】
技術的な知識はあまりないので、ホルダー寄りの意見で考えてみました。
もし、モナコインやリップル、サトシナカモトのビットコインなど慣れ親しんだ通貨の名前が変わるとしたら、もうそれは別物ですよね。
例えばですがモナコインがフォークしてモナキャッシュが生まれて正統になるとしても、モナコインの歴史は消えないので(派生サービスなどもふくめて)、モナコインとモナキャッシュが同時に存在することになると思います。
で、開発されなくなった旧モナコインが「モナコインこそが真のモナコイン」とか言い出す人もでてきそう。

【bitzeny orgの方を無力化する方法もありそう】
DoS攻撃ってやっちゃいけないんですね、訂正します。
bitzeny.techの方のＳＥＯを一位にもってくように頑張る(優良な被リンクをもらう)
bitzenyブランドを再構築したり周辺サービスを変えるよりは簡単そう。

【今進んでいるBitzenyコンテストや派生物がムダになってしまう(かも)】
もったいない、とかじゃなくて、皆で作っていくというコンセプトがあるのなら、皆の意思が集まってできたコンテスト結果をすべて白紙に戻すような方向転換は、その過程で関わってきた人たちを軽視しているようにみえるし、できつつあるコミュニティもなくなる可能性高いと思います。

**アンケート ２**
HFするのであればの話しで「Zenycoin(ゼニコイン)」とか、言いやすいかも。

趣旨ずれるけど、イーサリアムのやつみたいに新をbitzeny 、旧をbitzeny classicのもしっくりくる

主張がまぎらわしくてすいません。

**Comment by hitobb** [comment]
まずは技術的な視点から。

本日、現時点では、（手数料問題はありますが）以下の2つのチェーンに互換性はあります。

- BitZeny 1.x ブロックチェーン
- 現BitZeny 2.x以降のブロックチェーン

将来的にBitZeny 2.x以降のブロックチェーンを対象にSegWitがアクティベーションされた場合、2つのチェーンの互換性は失われます。

具体的には、BitZeny 1.x視点でみると『ソフトウェア公開後に開発された新機能』であるSegWitのブロックを認識できなくなる（＝BitZeny 2.xによって承認されたブロックを正常とみなせない）為、1.xを起因とする取引がうまく動作しなくなります。

本問題を解決するために見えている選択肢として、以下があります

- BitZeny 1.xのクライアント公開を止める( #32 結果にて、選べなくなった選択肢)
- HF宣言を行い、現BitZeny 2.x以降のブロックチェーンを別コインとして管理する
- 現状維持して、orgの検索ヒット率を下げる
- SegWitのアクティベーションをあきらめる（リスクとしてBTC 0.16以降の新機能が利用できない可能性がある）

ベストは創始者さんと意見交換を行い、1.xの公開停止あるいは2.xに代わる機能拡張を実施することでした。#32 となりましたので、次の選択肢となりますHF宣言の可否（2つ目を選ぶか3つ目を選ぶか）をアンケートしています。

最終手段として2.xの仕様変更部分を巻き戻し、SegWitをあきらめるという選択肢もあります。その場合は、将来的なポテンシャルが大幅に低下することを御認識して頂きたいです（もにゃを含めた、wallet系の新機能にも追随出来なくなります）

残念ながら、すべての要望を満たすベストな選択肢はみつかっておりません。

ｰｰｰ

次にマーケティング的な視点から。

取引所と交渉するたびに「bitzeny.orgの更新」「bitcointalk ANNの更新」を求められます。
#32 の結果から、更新できる可能性が現実的に厳しくなりました。
現在は全取引所と個別交渉の結果、ご納得頂いている状態ですが、正直、いつまで続けられるか疑問です。

HF宣言を行い、新たなANNを立てることで解決する課題ではあります。
現状維持、SegWitをあきらめるという選択肢もアリですが、前述のように、世間で流行っている新機能をBitZenyに求める事は出来なくなります。

ｰｰｰ

最後に私の立ち位置です。
私は今後、アトミックスワップが成功した、SegWitを前提としたコイン側を推します。
皆様の選択肢次第では、BitZenyコミュニティへ関わる比率が低下することをご理解ください。

以上となります。

**Comment by Aeinsk** [comment]
技術的なことには明るくないのですが後継通貨ではなくBitzenyの考え（CPUマイニング）を軸とした新通貨としてリリース（手持ちZNYは継承可能）は不可能なのでしょうか
この場合は現在あるBitzenyのブランドをほぼ捨ててしまうことにはなりますが…

**Comment by AkashiRiot** [comment]
私のようなじゃがりこに全裸でダイブするキャラがコメントするべきか悩みましたが、
意見を述べさせていただきます。

アンケート1
・賛成

賛成と反対で何度か考えが揺らぎましたが、BitZenyは現在大きな岐路に立っているため、一時的な問題は優先度を下げて長期的な視点を優先してもよいのではないかと考えるようになりました。

今後のBitZenyの発展を考えると重要な課題の一つは、
開発の労力に対して僅かな投げ銭報酬と知的な好奇心で開発してくれている開発者に対して、後に混乱する要素をできる限り取り除き、複数人の開発者が永続的に開発しやすい環境を整備することだと考えます。

まだまだBitZenyは再度駆け出したばかりで、可能な限り開発しやすい環境を整えておかなければ
コアの技術的進歩も鈍り、今後のサービス層の発展も利用層の広がりも遠ざかると考えます。

今回では新たなコインとすることでANNや公式サイトなど正しい経路での最速の情報伝達を可能にし（他コインなら当たり前のことですが…）最新の技術を取り込んだり生み出せる環境をつくり、創始者に絡む批判や混乱も今後一切発生しません。
このまま「BitZeny」とそのままにしておけば、創始者のいつ出るかわからない再コメントでコア開発が止まったり方針転換もあり得るのではと考えています。

後は、取引所の引継ぎが問題視されていますが、今既に上場している全ての取引所について、全て受け入れてくれる必要はないようにも思えます。
流石に取引所ゼロは厳しいですが、実際CryptoPiaかCrypto-Bridgeのどちらかの取引所が対応してくれれば、他の取引所は取引量もごく僅かで現状と比較してユーザ層の利便性は大きく損なわれないようにも思われます。（各取引所の上場に動いていただいた方のことを考えると心苦しいですが…）

短期的な波乱は含んだとしても、新しい技術革新を推し進める開発陣で新しい名前でハードフォーク宣言をしてもよいのではないでしょうか。


アンケート2
・ZenyNext

自分のネーミングセンスがなさすぎて吐きそうです。

**Comment by manpuku023** [comment]
アンケート１　賛成
（理由）
１）BitZenyが進化していくために必要と考えるので
（他のコインが進化してく中、BitZenyだけが現状維持するのは退行していくのと同じと考えます）
２）関連して、リネームも必要と考えます。
（BitcoinTalkの更新不可、公式HP、Twitterアカウントが譲渡されない今のデメリットが大きすぎます）

アンケート２　名称案は４ないし５案をクローズで検討し、Twitterの投票で決定
（理由）
１）.orgドメイン、Twitterアカウントを押さえたうえで選考する必要がある
２）すでに権利設定されているものかどうかチェックしてから選考する必要がある
（登録済み商標などに当たっていないかチェックする）

**Comment by hitobb** [comment]
> ２）すでに権利設定されているものかどうかチェックしてから選考する必要がある
（登録済み商標などに当たっていないかチェックする）

これ、大切ですね。
具体的には「Zeny」という文字列は商標登録されているので、利用できないです。

**Comment by doisatoshi** [comment]
アンケ参加させていただきます。

アンケート１　賛成
BitZenyが技術的にも遅れがないことや進化していることを認めてもらうためにも必要と考えます。

アンケート2     BitZeny Primary
変化や進化に柔軟なものが主要な存在だと信じております。

**Comment by SAMUJAPAN** [comment]
アンケート１　賛成

アンケート２　ZNY(ゼットエヌワイ)
Zenyがダメなので。こちらは商標の問題はなさそうです。

**Comment by TomTomKick** [comment]
アンケート１　賛成
言い方は悪いですが、現状のコミュニティ規模であればまだ混乱も抑えられるのではないかと思います。

アンケート２　BitaZeny（ビタゼニ）
・Bit A Zeny　：我こそビットゼニーという気持ちを込めて
・鐚銭　：旧公式に対する皮肉的な自虐を込めて

**Comment by naoki-satou** [comment]
アンケート1  賛成

○HF 無しで完全に問題が解決できる方法が無いと思われるから。

○現在BitZenyに関わっている有能な技術者が新しい技術を発揮出来る場所で有って欲しいから。

○これは、私の気持ちの問題ですがHFした方が前に進んでいる前向きなイメージがあるから。

○ZNY

**Comment by macyan2000** [comment]
アンケート１ 賛成
いつまでも旧規格コインのままでいいの？

アンケート２ BitZeny Destiny
某ロボットSF系アニメでも使われた単語ですが、
まさに運命とか宿命を背負った通貨になるでしょう。

**Comment by elsinoe** [comment]
Q1. お任せします(技術的には必要と思いますが名称問題が絡むので現時点では賛否言えません)
Q2. Ethereumのように、v1.xをBitZeny Classicとしv2.xはBitZenyのまま存続させるのがよいと思います

**Comment by yenxrutile** [comment]
私的な見解ですが。
現状のBitZenyから2つの派閥(HF)が生まれて片方がcalassicを名乗るとかであれば理解出来るのですが、オリジナルに勝手にcalassic付けようと言うのは、_oldを恰好良く言い換えただけに思えてしまい違和感を感じました。
また、org、bitcointalk、twitter、及び"BitZeny"に紐付く古い情報が残り続け、名前は同じだけど別物だよ、と言う状況を認知させるために多大な労力が掛かるように思います。
デザイン資産など引き継げない物が沢山出てしまいますが、今回のHFに関しては、元のBitZenyと別物であると言う事をわかりやすくする事も大きな目的の一つになると思います。

**Comment by bellflower2015** [comment]
根本的な話でアレなんですが
これ、「日本語だけで」議論してていいんでしょうか？

**Comment by kazkit** [comment]
アンケート 1
賛成

HFでこそどちらが支持されるのか示されると思うのですが、迷っているならGitHubよりtwitterでアンケート取ったほうが意見が聞きやすいように思います。

アンケート 2
CatZeny

Zenyの名前が気に入ってるのでそれが入ってればいいかなぁ。
コードネームをバージョンアップでアルファベット順に付けて何かのキャラクタに表現するような慣例を採用してはいかがでしょうか？Bitの次はCなんとか。Cの次はDなんとかのように。
銭猫ならキャラクタ化しやすくないです？

**Comment by zenyman5** [comment]
アンケート1
賛成

アンケート2
思い切ってストレート「Zeni」
慣れ親しんだ「Zeny」のみでもいいですが。

やはり目指すところは決済手段としての仮想通貨だと考えます。
５年後、１０年後、日常で円の代わりに使われてることが我々のゴールですよね？
その際には、長い名称は使いづらいです。
シンプル、言いやすい、親しみやすい、日本らしいが一番。

**Comment by zenyman5** [comment]
アンケート1
賛成

アンケート2
思い切ってストレートに「Zeni」
慣れ親しんだ「Zeny」のみでもいいですが。

やはり目指すところは決済手段としての仮想通貨だと考えます。
５年後、１０年後、日常で円の代わりに使われてることが我々のゴールですよね？
その際には、長い名称は使いづらいです。
シンプル、言いやすい、親しみやすい、日本らしいが一番。

**Comment by zenyman5** [comment]
アンケート1
賛成

アンケート2
「Zeni」

慣れ親しんだ「Zeny」のみでもいいですし、短い名称がいいです。
なのでBitzeny+○○反対です。

決済手段のスタンダードとしての仮想通貨になって欲しいし、
５年後、１０年後、日常で円の代わりに使われてることが我々のゴールですよね。
その際に、消費者も店舗も企業も長い名称（正式名称でも）なんとなく受け入れ難いです。

子供もお年寄りも言いやすい、親しみやすい、シンプルで日本らしいが一番。

**Comment by zenyman5** [comment]
アンケート1
賛成

アンケート2
「Zeni」

慣れ親しんだ「Zeny」のみでもいいですし、短い名称がいいです。
なのでBitzeny+○○反対です。

決済手段のスタンダードとしての仮想通貨になって欲しいし、
５年後、１０年後、日常で円の代わりに使われてることが我々のゴールですよね。
その際に、消費者も店舗も企業も長い名称は（正式名称でも）なんとなく受け入れ難いです。

子供もお年寄りも言いやすい、親しみやすい、シンプルで日本らしいが一番。

**Comment by Aeinsk** [comment]
HFに関してするしないの決定にかかわらず事前にHFに向けての調査をするチームくむとスムーズにいくと思います

**Comment by hitobb** [comment]
@bellflower2015 
bitcointalk.orgでお伺いを立てるのが良いかなと思います。
皆さんも遊びに来てね。

@Aeinsk 
HFについての調査とは、具体的に何を行えばよいでしょうか？
取引所への影響でしょうか？それとも、BTCのソースに関する調査でしょうか？
また、必然的に（上場資金を立て替えているので）「古参」と呼ばれている方々の比率が高くなるので、バランスをとるために旗振りは第三者にお願いしたいと思いますが、いかがでしょう？

**Comment by hitobb** [comment]
そろそろ意見も出そろった感があるので、いったんまとめに入りたいと思います。
ご意見を記載されていないかたは、12日までに書き込みをお願いしたいです。

どうぞ、よろしくお願いいたします。

**Comment by Aeinsk** [comment]
自分の考えていたのは現在Bitzenyを取り扱っている取引所のHF後のコインの取り扱い（費用等）やHF後の現在のZenyコミュで開発されているサービスの新コインへの移行が可能なのかなどの調査です。
個人的な考えを書かせていただきますと私はオープンな組織化賛成の考えなのでHF後も一般企業でいうところの経営、企画、広報などの業務に引き継げるチームが理想と考えています。

**Comment by hitobb** [comment]
@Aeinsk
過去の私の投稿にもありますが、上場時に資金を提供したアカウントからの相談であれば、HF後の新コインへの移行交渉が可能と判明しています。その際、bitcointalkとgithubのソース、場合によってはホワイトペーパーが求められます。調査結果としては以上ですね。

オープンな組織には賛成です。ただ、上場資金数百万相当を、過去、立て替えてくれた古参の方々を完全排除するのが本当に透明な運営か、という点においては疑問を投げ掛けておきます。

CB、Cryptpia、stocexchange、失敗しましたがyobitへの上場資金を寄付していただいています。

**Comment by BitzenyDevTeam** [comment]
お疲れ様です。
遅くなりましたが、、
1）　その他
正直まだオルファさんを待ってるので心情的には待ちたい。
でも新コインとして分離すると、より濃い形でWPも作れるだろうし確実に基盤がしっかりした面白いものを作っていけると考えています。
いずれにしても、どっちに転んでも良いようには準備してます。

2）あっしに名づけの才能はありませんｗ　ByteZenyとかKiloZenyとかMegaZenyくらいか。。。

**Comment by znycloud** [comment]
アンケート1
反対
       FFの場合、現存の $ZNY が電子ゴミになり、Bitzenyのブランドをほぼ捨てることになります。
       例えば、現存の $ZNY は、Segwitの方向ではなく、bitcoinCashと同じように、blockchainサイズ拡大する方向にすることはできますでしょうか。この場合、monacoinと差別化も出来ます。

アンケート2
                 bitzeny(新) 、bitzenyClassic(旧)

bitzeny(新) の公式サイトは、bitzeny.tech、旧公式 http://Bitzeny.org  などは、BitzenyClassicの公式サイトだと宣言すれば、解決することもできると思いますが、。
（一番ベスト方法は、やはり、Bitzeny創業者と話し合い、解決することですが）

**Comment by hitobb** [comment]
残念ながら、blockchainサイズ拡大も、ハードフォークになりますね、、、

**Comment by cryptozeny** [comment]
1.中立:
HF宣言はしても良いし、しなくても大丈夫です。 中立です。 

2.反対:
しかし、名前の変更には反対します。 現在まで培ってきたイメージが損なわれる恐れがあります。

**Comment by cryptozeny** [comment]
1.反対:
率直な心情からは時間がかかってもオリジナル開発者の返事を待ちたいです。 

2.反対:
現在まで培ってきたイメージが損なわれる恐れがあります。

**Comment by zenywallet** [comment]
アンケート 1
反対
技術的なハードフォークでなく、エアクオートで"Hard Fork宣言"という
だけのものであったとしても、ハードフォークはブロックチェーンにとって
価値低下につながると思います。
Bitcoinではスケーラビリティ問題を解決するためにハードフォークはせず、
segwitによってソフトフォークで解決しています。

ハードフォークで分裂した新たな通貨を作るという話であれば、そういった
活動グループがあってもよいと思います。一度ハードフォークして分岐した
通貨は、Bitcoin Cashのように将来的なハードフォークが容易になると思います。
ただ、オリジナル側のチェーンはハードフォークするべきではない
と思ってしまいます。なぜそう思うのか分かりませんが．．。

アンケート 2
ZenyCash
zenyhime

ハードフォークしない場合でも、ZenyCashプロジェクトとして、
オリジナルBitZenyのブロックチェーンを永続的に維持しつつ、
新しい機能が使えるCoreをZenyCashとしてブランディング
していく方法もあると思います。

**Comment by nagasench** [comment]
アンケート1
賛成

アンケート2
bitzeny(新) 、bitzenyClassic(旧)とするのが良いと思います。
Zenyが商標登録していて使いづらいのであれば、BitYenとかにするのが良いかと。

**Comment by silneko** [comment]
なかなか意見が固まらず、書きあぐねておりましたが、期限とのことなので現時点での思いの丈を綴っておきます

**1. Hard Fork宣言について**
現時点の情報ではどちらともいえません

HF自体については、今後機能追加などしていくにあたっては「不可避」なものだと思っています。
ですが、今回のように「公式情報の編集権限が譲渡されていない」という原因からのHFに関しては、素直に賛成とは言い難い気持ちが強いです。

しかし、HFを否定する、ということは実質z2.xで開発がストップするということでもあると思っており、（創始者様が再帰還してフルコミットでアップデートしていくなどの大逆転劇が無い限りは）今後の技術的な展望が見込めないとも思っています。

私個人のBitZeny参入の経緯として、価値の上昇を期待するよりも、技術的発展を見ていきたいという思いのほうが強かった為、そういった意味では、HFは賛成になります（ややこしい）

**2. HFする場合の新コイン名称について**
基本前提として、新コインが BitZeny と名乗ることが出来る道があるのであれば、それを支持したいです。
その場合、HFも手放しで賛成出来ると思います。

HFするにあたって、新コイン側の名称の変更が必須要件となるのであれば、以下の案でお願いします。

BitZenyPlus
もしくは
ZenyPlus

また、新名称に関して「略称」「呼称」「通貨コード」なども含めて検討できるとよいかと思いました。

自分の案だと BZP とか ZNP とかちょっと語呂よくない感じもしますが・・・
BitZeny ($ZNY、ゼニー、ぜにぃ) という語感の良さで愛されていた部分も少なからずあると思っていますので。

**Comment by cryptozeny** [comment]
付言:
アルゴリズムの変更とか技術的な進歩によってHFするのはいつでも賛成です。 しかし、団地の開発者と連絡がつながらないという理由は反対します。 

HFは非常に難しい作業であり、然るべき理由がなければなりません。 それだけでは妥当性が不足します。

**Comment by sesameoil** [comment]
期限ぎれで申し訳ないのですが、意見を書きます。
### アンケート1.反対
少しずつz.2.xが認知されてきた状況で、HF宣言をすることはさらなる混乱を生むのではないでしょうか。
実際、私の身内の中でも混乱している人もいます。
また、ドメイン名レベルでBitZenyの名前を取り入れているサービスも多く、新znyに追従する場合、ドメイン変更、サービス名変更等を強いることになってしまい、混乱が更に拡大すると考えます。

逆に言うと、しっかりと広報を確立し、サービス開発者等を支援し、混乱を防ぐことができる体制ができるのならHFは賛成です。
いずれHFは避けられないことです。
### アンケート2.
もし行うなら、「BitEazy」というのはどうでしょうか。
easyがeazyなのはわざとです。

CPUマイニングよって手軽に始められるという「Eazy」です。
また、「z」と「y」の文字と音が残っているので、znyからHFしたことが意識できると思います。

**Comment by hitobb** [comment]
皆様、ご意見ありがとうございました。
僭越ながら取りまとめさせていただきます。

## アンケート１
なかなか悩ましい結果になっています。

- これまでbitzenyサービス開発等に関わって来られた方々 : HF宣言、反対が多数
- 投資家の方々 : HF宣言、賛成が多数

単純に多数決に従えばHF宣言ですが、実際に手を動かして下さっている方々の理解が得られていないので、開発が大幅に滞る可能性が高いです。
よって、

# 本日、現時点ではHF宣言をしない

を、いったんの結論としたいですがいかがでしょう。
これは恒久的にHFしないということではありません。
５月の時点では準備不足なので宣言なし、継続協議という意味です。

## アンケート2

zenywalletさんのご意見がステキと思いました。
HFの有無とは関係なく、区別するために名称のみリブランディングするのはいかがでしょう？
本提案が受け入れられるのであれば、HFとは別の作業として「ロゴコンテストのように」独立させて活動できます。

以上となります。
本まとめに対するご感想、お待ちしております。

**Comment by Aeinsk** [comment]
私は今回のまとめについて1、2ともに賛成です。
将来的なHFに向けての検討なた支援体制を整えるよい機会だと考えています。

**Comment by AkashiRiot** [comment]
意見を取りまとめていただいたhitobb氏の結論を支持します。
私は迷った挙句HF宣言へ「賛成」としましたが、現状の意見の割れ方であればコミュニティができる限り分断されることなく進められる現時点ではベストな判断だと思います。

これからの話かとは思いますが、背景の１つとして挙がっていた「ANN」や「bitzeny.org」はリブランディングに合わせて、ANNは新規で投稿し直し、ドメインは取得して通知していく方向性なのでしょうか？

**Comment by manpuku023** [comment]
hitobbさん、取りまとめありがとうございました。
現時点でHF宣言しない、とのまとめを支持することといたします。
引き続きよろしくお願いいたします。

**Comment by yosio831** [comment]
現時点ではHF宣言をしないということで了解しました！
リブランド名称を決めて周知させたうえでHFありだと思います。
その場合、既存のサービスが対応しやすいように「ゼニー」という語感は残していってほしいと思います！

**Comment by bellflower2015** [comment]
@hitobb まとめありがとうございます
リブランディングするなら、BitZenyの語感は跡形もなく全く違う名称にするのが良いと思います。

**Comment by znycloud** [comment]
@hitobb さん　まとめありがとうございます！
私は今回のまとめについて1、2ともに賛成です。
zenywalletさんのご意見は確かに素敵だと思います。

**Comment by hitobb** [comment]
おおむねご意見が出そろいました。
特に反対意見はなかったようですので、本件クローズといたします。
