### ISSUE TITLE
BitZenyに採用されているBIPの管理について

### ISSUE THREAD

**Issue by hitobb** [BitzenyCoreDevelopers/others#36]
## 前提知識

BIPは「Bitcoin Improvement Proposals」の略です。
インターネットにおけるRFC「Request For Comments」と同様の位置付けとお考え下さい。

## 問題点

BitZenyに組み込まれているBIPのフラグを一目で把握できる仕組みがない。

## 提案

BitCoinのBIP管理方法を参考に、BIP管理を可視化する。
フォーク元（予定）：
    https://github.com/bitcoin/bips.git

### メリット

BitCoinとの実装差が把握できる。
ソフトフォーク/ハードフォークに関するBIPの存在が認識できる。
BitZenyのBech32プレフィックス等、取り決めした内容が一目で把握できる。

### デメリット

管理対象ドキュメントが増える。

ｰｰｰ

上記活動について、まずは本日から2週間でご意見を募集します。
賛成・反対・その他率直なご意見をお伝えください。
よろしくお願いいたします。

**Comment by yenxrutile** [comment]
作成コストに対し、多数の人が恩恵を受けられる物でしょうか？
BTCの差分を詳細にする事で、悪用されるリスクはありますでしょうか？

**Comment by cryptozeny** [comment]
賛成:
あったらいいなと思います。 まず日本語で翻訳が必要なんですか?

**Comment by onokatio** [comment]
賛成
現状開発陣しか使わないけど今後BIPを含めるか含めないかの話し合いをしたり、まとめたりするのが楽になるため

**Comment by silneko** [comment]
名称の議論(#37)が活発でこちら動きが無くなってしまっているので、意見いたします

賛成
この機能を実装するためにはHFが必要だよ、などの情報は開発内/外共に有益に働き、話し合うための情報がわかりやすくなるとともに、
第三者から見ても最新技術への追従、活発な開発状況をアピールできる資料にもなるかと思います。

**Comment by sesameoil** [comment]
賛成
BitZenyの対外的な情報は不足しており、その解決策の一つだと考えます

**Comment by hitobb** [comment]
みなさま、ご意見ありがとうございます！

BIP管理、実装する方向で準備を始めます。

**Comment by yenxrutile** [comment]
お茶を濁してしまってすみません。開発タスクの追加に関してなので是非もございません。
BIPの仕組みに関していろいろ情報集めてみます。

**Comment by kaminuma** [comment]
賛成。

勉強しやすくなる気がします(笑)

**Comment by hitobb** [comment]
試験的に、bitzenyPlus側のorganizationsにBIP設置しますね～

**Comment by hitobb** [comment]
本プロジェクトは、BitZeny Plusに引き継がれました。

https://github.com/bitzenyPlus

以上、ご報告いたします
