### ISSUE TITLE
BitZeny 新名称（投票）

### ISSUE THREAD

**Issue by hitobb** [BitzenyCoreDevelopers/others#38]
#34 #37 から派生した議題となります。

#37 にて募集した名称の中から、投票数の多いもの上位3つをリストアップしました。
下記3つの候補から1つを選出したいと思いますので、皆さんのご意見を募集いたします。

**「BitZeny Core」
「BitZeny Plus」
「zeny」**

新名称募集は2018年6月10日を以て終了しております。
また、 #37  にて複数名の賛同を得なかった候補名は候補から外しております。
もれがありましたらご指摘ください。

## アンケート

適切と考える理由
あるいは、適切ではないと考える理由

## 期間

2018年6月20日まで募集
なお、本議論で決着がつかなかった場合は、
最も投票数の多かった「BitZeny Core」に確定いたします。

以上、よろしくお願いいたします。

**Comment by silneko** [comment]
BitZeny Plus 推しです。

理由としては、「新しいものであること」「機能が追加された(されていく)ものであること」が一目で分かりやすい所と、いい意味で「普通っぽい」ところです。

zeny については、名称変更の理由の一つである「情報の混在」を避けるためには少し弱いかな、と思っています。

BitZeny Core については、個人的に懸念点がありますので #37 で書いたものをこちらにも引用しておきます。
(反論、こういう所が推しというご意見をお待ちしております)
> まず、もし創始者さんが戻られた時に、元のソースから開発再開されても支障が無いように、という前提があるとして、
> 
> 1.「Core」自体の意味について
> 
> 「Core」自体には「核」とか「芯」という意味があるかと思いますが、前提の「元のソースから開発再開されても支障が無いように」ということを考えると、こちらを「核」と言ってしまってもいいものなのか、という懸念があります。
> 
> また、このリネームの経緯や知識の無い方が、
> 
> 「BitZeny」「BitZeny Core」
> 
> という２つを並べて見た時に、「Core」が付いている方が大元になった方なのか？、という風に誤認してしまう懸念も考えられます。
> #32 の時にも、一部で「乗っ取りだ」など言われてしまっていた事もあり、「こちらが真のBitZenyだ」と主張していると捉えられかねない（もちろんそんな意味ではない事は承知しておりますが）懸念は避けたいところかと思います。
> 
> 名前から「こちらが新しい方」「機能が増えている方」だと分かりやすいほうが良いのではないかと思っております。
> 
> 2.開発側の目線が強い
> 
> 「BitZeny Core」の案の元として、開発チームである「BitZeny CoreDeveloper」から来ているところが大きいと思いますが、開発サイドの目線が強く出過ぎていないか、という懸念があります。
> 
> BitZenyはこれまでも、投げ銭はじめいろいろな副次的サービスの開発もあって存続してきた経緯もあると思います。
> そんな中で、開発チーム名からの名称となってしまうと、「開発サイドの意見がより尊重される」というように感じられてしまう場面もありそうで、それがマイナスに働いてしまうことがあるかもしれないと思っております。
> 
> 「内輪ノリが強くて参加し辛い」とか、「GitHubで議論されている状態は閉鎖的だ」という意見も一部で出ている中、「開発チームの名前から新名称が決まりました」となると、それらの不信感がさらに強まってしまわないか、という懸念があります。

**Comment by CryptoTigerAxiom** [comment]
新名称投稿：BitZeny Plus

理由： #37 にてBitZeny Coreを最終的に推しましたが、 @silneko さんの意見や他の方の意見、また将来的な事や、他の通貨名称、今後の開発などを総合的に鑑み、Coreという名称を通貨そのものにつけるのは混乱を生じる可能性があると感じました。

そのため「オリジナルがBitZenyであるという事」、さらに「オリジナルから進化を遂げたという事」を名称から感じやすい、BitZeny Plusが最も妥当であろうと考えております。

**Comment by onokatio** [comment]
BitZeny Coreに一票

BitcoinがBitcoin Coreでまかり通っているので特に問題ないかと

**Comment by zinntikumugai** [comment]
`BitZeny Plus`に一票

理由
`BitZeny Core`はBitZenyのWallet、`BitZeny Core`と被る
その他の通貨のWalletは
```
〇〇 Core - Wallet
〇〇 - Wallet
```
のいずれかが多く採用されており、`Wallet`を採用(Walletの名称からCoreの削除)しちまえばいいじゃんとか思ったが、末尾に`Wallet`のみあるものは主にPOS系で、POW系は**ココ最近のものは**`Core`と付ける傾向にある
(ベースバージョンが極端に古いものはCoreがつかないようです,saya, sakura, sha1など)
例えば`BitZeny Core - Wallet`としたら今までのWalletの名称として不自然な感じが出てくると思いました
(まぁそんなところ気にする人少ないと思いますが一部の人は出る可能性はある)
あくまでもFork元Walletがそうしてきたためそうなったとも言えるが、多くの通貨でCoindWalletはCoreと名付ける点で`BitZeny Core`は一部の人は`BitZeny`という通貨のWalletを指したものと見れるかもしれません

よってリブライングしたため余計誤解を生むことになると思います(そうなったらリブライングの意味がない)

~~もっとも提案時にもうちょっと意見しとけよと自分に言いたい
`Core=Wallet` 脳~~

**Comment by cryptozeny** [comment]
`BitZeny Plus`
coreはcore walletおよびcore devを指すので混乱の恐れがある。

**Comment by ghost** [comment]
BitZeny Core

**Comment by manpuku023** [comment]
1）ZENYを条件付き支持します
・条件は、やはり権利関係に問題がないこと、ですね。

もし1）が条件クリアできなければBitZeny Plusで。

理由）初めてBitZenyに触れた方が戸惑わないように配慮したほうが親切と感じるため。
（BitZeny coreも悪くないですが、その都度答えなければいけないことを思うと気が重くなります）

**Comment by Tanisun** [comment]
私は

BitZeny Plus

に一票で！

**Comment by SYMonorch** [comment]
zeny

シンプルイズベスト
付属の言葉がついてると
新規の人が何が何やらわからないと思います

**Comment by YNM-Kun** [comment]
BitZeny Plus

個人的な理由でぜにぷらっていう可愛らしい(?)あだ名で呼べそうだから

**Comment by kaminuma** [comment]
任せる！

**Comment by yomo3** [comment]
BitZeny Plusを支持します。

zenyはシンプルでわかりやすいと思います。何の障害も無ければこちらを支持したかもしれません。

BitZeny Coreという言葉は、BitZenyオリジナル側の何か(技術範囲等)を指し示す為に使うのが適切なように思います。

**Comment by nonashi01** [comment]
自分は問題が起こる懸念があっても、実際に問題が起こってからその都度解決していくなり妥協点、鞘に収まる方法を模索したり、選んだ際に予防線を張るなりしていけばいいと思ってるので
個人的なセンスでbitzeny coreを推します
ただ、予防のためにplusを推す考えは支持してます

**Comment by spacecodes** [comment]
投票は断念します。もう一度意味がわかりやすいLiteZenyまたはBitZeny Cashをご検討ください・・・（諦め悪い）

zenyはシンプルでいいけどZennies($ZENI)という通貨がCoinMarketCapで1050位にいます。
BitZeny PlusはBitcoin PlusがCoinMarketCapで685位とふるってないのでCashやGoldの方が良さそうに感じます。
BitZeny CoreはCoreチームの意味があるのですごく紛らわしいと思います。

以上を踏まえると３つともに認知されにくいと思われますので投票はできませんでした。

**Comment by LUPIN2** [comment]
BitZeny Plus に1票です。

**Comment by yenxrutile** [comment]
BitZeny Plusを支持致します。

現状、"bitzeny core"で検索すると、"bitzeny"のウォレットの説明サイトや"bitzeny"に紐付く情報が上位に出て来ますので、"bitzeny"から"bitzeny core"への移行時期は混沌を極め、新規の人の参入障壁になる恐れがあると思います。
意味や響きは良いと感じていますが、当初のリブランディングの大目的である、```BitZeny 1.x ブロックチェーンと、現BitZeny 2.x以降のブロックチェーン混在を避けるため```を満たせませんので、不可だと思います。
"Zeny"に関しては、"BitZeny"の文字列をそのまま維持する方針に賛同しますので不支持です。

**Comment by AkashiRiot** [comment]
かなり迷いました…
選ぶにあたって自分なりに各案には
以下のような長所・短所がありました。

▼ZENY
【長所】
文字数も短くシンプル。
現在、企業（BlockchainLab株式会社）が申請中だが拒絶理由通知書を受けている状況。
もしこのまま申請期間を過ぎて商標権が誰にも取得できない結果になれば、非中央集権らしいネーミングで望ましいのではないか。
【短所】
現在は拒絶理由通知書が出されているが申請している法人の最終結果を待たなくてはならない。

▼BitZeny Core
【長所】
最も支持が多い。Coreという言葉にも親しみがある。
【短所】
オープンソース、開発者、Walletを差す場合と混乱してしまう懸念がある。
（解決策として別途それぞれ呼び方を規定するものよいか？初心者には説明が必須か…）
BitZeny CoreOSS , BitZeny CoreDEV , BitZeny CoreWallet

▼BitZeny Plus
【長所】
混乱しにくく新しいことが分かる。
【短所】
特にないが…「Plus」にそれ程込められた意味があるのかと言われたらあんまりないような…


純粋にネーミングだけで判断するなら「ZENY」となりますが…
「ZENY」は商標登録が拒否されるという条件があり締め切り日に判断しないことになりますので
今回の提案条件から考えると厳しいのかなとも考えています。

上記の理由から消去法的な選び方ですが「BitZeny Plus」を支持します！

**Comment by kojisarukawa** [comment]
新規参入の方に受け入れられやすいのは何か？迷わないのは何か？を観点に考えてみました。
「BitZeny Plus」に一票です。
理由は、Plus（プラス）が
・意味そのものが発展的であり
・コピーライトの側面からパ行は言いやすく覚えやすい
からです。
意味そして言いやすさ覚えやすさも隆盛のための一つの要素なのでは、と考えました。

**Comment by glen040417** [comment]
BitZeny Plus に一票です。

**Comment by glen040417** [comment]
「BitZeny Plus」に一票です。

**Comment by Marimox** [comment]
私もBitZeny Plus派です。
シンプルに分かりやすくBitZenyの後継であることを示せているので。

**Comment by gufutokku999** [comment]
BitZeny Plusを支持します。

**Comment by balloonfc-hub-git** [comment]
（やっとアカウントが作れました・・・）
BitZeny Plusでおねがいします！

Coreは良いのですが、やはり他との被りが気になりますね。
Plusなら、レベルアップ版というのもわかりやすいと思います！

Zenyはちょっと寂しいかな。

**Comment by hitobb** [comment]
みなさま、ご投票ありがとうございました！

賛同多数でしたので「BitZeny Plus」を採用させていただきます。

■直近のアクション

・「BitZeny 3.0」プロジェクトを「BitZeny Plus 3.0」プロジェクトに改名し、活動再開します。
・「BitZeny 3.0」ソースには、旧ロゴは含みません。新ロゴ1本で行きます。
・将来的にハードフォークが必要になった場合は「BitZeny Plus」としてBIP管理します。同意できない方は「BitZenyのフォーク」として活動してください。誰であっても止める権利は持ち得ません。

以上となります。
反論ありましたら、１週間以内にお願いします。無ければ次のステージな進めますよ～

よろしく～

**Comment by nonashi01** [comment]
よろしくお願いします

**Comment by hitobb** [comment]
本件、特に反対意見なしと認識いたしましたので、クローズします。
皆様ありがとうございました。
