### ISSUE TITLE
BitZeny Plus 3.xプロジェクト

### ISSUE THREAD

**Issue by hitobb** [BitzenyCoreDevelopers/others#39]
（bitzeny.infoにも同様の投稿をさせて頂きました。回答しやすい方法でコメントを頂けると助かります）

■背景

・SegWitがアクティベートされたので、BTC 0.16への移植が可能になった。
・ロゴコンテストにて決定したロゴのみを含むqtを作成したい。
・今後のハードフォークを想定した、新ネームが確定した。

■方針
・現BitZeny 2.0をフォーク元として、新リポジトリを作成。
・新リポジトリ名は「bitzenyPlus」
・Branchはz2.0.0/2.0.1以降のみを残す（＝オリジナルbitzenyとの枝分かれ）
・ロゴアイコンは、コンテストで決定したもののみを残す
・リリースポイントは、2.0.0以降のみを残す（＝1.2.x系は削除する）

これらを踏まえたうえで、

・BTC 0.16をベースとした「BitZenyPlus 3.0」を開発します。

■なぜ、このようなことをするか？

将来のハードフォーク（アルゴリズム変更など）に備えるためです。
逆に言えば、ハードフォークが起こるまでは現在のまま、互換性保持です。

■現在のbitzenyリポジトリはどうするか

残します。
今後、1.x系統、あるいはPlusと異なる2.x系統の開発を行う誰かのために永久保存します。

■それでは、organizationも分けたほうが良いのではないか？

将来のハードフォーク（アルゴリズム変更など）が起きたタイミングで分岐させます。
現時点では互換性が保てているので、organizationを分ける必要を感じません。

■SegWit互換が目的であれば、z2.0.xで十分ではないか？

現時点で以下の問題が発生しています。
・segwit対応アドレスがコマンドから発行できない。
・Ubuntu18.04対応

しかしながら、BTC 0.16をベースにした場合、以下の問題も発生します。
・getinfoコマンドの廃止（Pool運営者への影響大）
　（※これはBTCが現在直面している課題でもあります）

ゆえに、2.0.xはそのままに、3.0.xを別リポジトリとして新規作成する方針です。

■Pool運営者はどうすればよいのか？

z2.0.xを引き続きご利用ください。
アルゴリズムを変更しない限りにおいて、互換性は保てます。

以上、ご協力、よろしくお願いいたします！

**Comment by hitobb** [comment]
現時点では使う予定はございませんが、organizationを予約取得しておきました。

https://github.com/bitzenyPlus

メンバー募集中です。
参加してみたい方はここにコメント or 個別にコンタクトをください。

**Comment by shuichiro-makigaki** [comment]
> メンバー募集中です。

メンバーになりたいです！

**Comment by hitobb** [comment]
@shuichiro-makigaki 

お誘いしました！

**Comment by cryptomamiya** [comment]
一応下記の動作報告
>しかしながら、BTC 0.16をベースにした場合、以下の問題も発生します。
>・getinfoコマンドの廃止（Pool運営者への影響大）
>　（※これはBTCが現在直面している課題でもあります）

BTC 0.16にてプール構築可能か調査しましたが、やはりコマンド発行部分でエラーがでとります。
といってもbitcoin-cliを使えば同等の情報は出せるので、気合で直すことは可能なレベル。
とりあえず互換性あるなら2.0でいくけど、いずれBTC0.16ベース対応はせなあかんね。

**Comment by hitobb** [comment]
BitZeny Plus側にも、issue置き場を作りました。

https://github.com/bitzenyPlus/others

以降の議題はこちらに移動します。

---

ソフトウェア開発には「安定版」と「新機能実装版」の２つを同時平行で進めるという手法があります。

安定版=bitzeny
新機能実装版=BitZeny Plus(失敗したら切り捨てられる可能性あり)

という住み分けにしたいです。
もし、新機能実装の過程でハードフォークが避けられないのであれば、そのタイミングで宣言します。

以上、いかがでしょう？

**Comment by sesameoil** [comment]
ややこしくなるだけだし、無印切り捨ての方向性がいいと個人的には

**Comment by hitobb** [comment]
最終的に開発をPlus1本化する点は同意します。ただ、今じゃない気がしてます。bitzeny Plusの開発が起動に乗ったら、無印は開発終息(だれかが引き継ぐ分にはご自由に)で良いかなと。

YesPoWer 0.5がどれ程のものかが掴めない時点で切り捨てするのは怖いです。
argon2の時のように、テストネットで実装したら起動遅くなりすぎ云々が出てくるかもしれない。

**Comment by sesameoil** [comment]
なるほど
YesPoWerの実証が終わるまでは無印もサポートするということですね
そのことに同意します。

**Comment by hitobb** [comment]
本プロジェクトは、BitZeny Plusに引き継がれました。

https://github.com/bitzenyPlus

以上、ご報告いたします。
