### ISSUE TITLE
bitcointalkの引き継ぎ

### ISSUE THREAD

**Issue by yenxrutile** [BitzenyCoreDevelopers/others#6]
https://bitcointalk.org/index.php?action=profile;u=385912
現状、"BitzenyDevTeam"で応急措置を取っているが、本アカが稼働していないためdeadcoinに見えてしまう。

・誰が引き受けるにしても、各種英語対応の負担増
・とりあえずで預かるわけにもいかないので、運用方針、体制を確定させてから提案
・広報管轄で、英語対応してもらう人に報酬を出すような方式が無難か

**Comment by hitobb** [comment]
はい、これは明確な課題です。
英語対応できるメンバーは何人かいるので、言葉の課題はそこまで問題ではありません。
運用方針、体制、アカウント問題の改善が急務です。

**Comment by hitobb** [comment]
#32にて、本件は実現不可能になったという認識です。

@yenxrutile 
本件、クローズとして良いでしょうか？

**Comment by yenxrutile** [comment]
はい、引き継ぎ不可の認識で承知致しました。
本件クローズとさせて頂きます。
