### ISSUE TITLE
ぜにぃ姫跡地問題

### ISSUE THREAD

**Issue by yenxrutile** [BitzenyCoreDevelopers/others#7]
https://twitter.com/zenyhime
・6000フォロワー付きのBitzeny関連アカウントが死蔵されるのはもったいないので
　何かに再生出来ないか、と言った議題
・qaleghnes氏から譲渡希望を発したものではない
・交渉の余地が無かったり、既に結論が出ているようでしたらクローズ致します。

**Comment by hitobb** [comment]
これは私の個人的意見であることを先に述べておきます。
また、ぜまりんさん本人とは会話しておりません（コンタクトはすぐ取れます）

ぜにぃ姫の原案者である、ぜまりんさんがTwitterを引き継ぎ、
オフィシャルなツイッター化するべきではないかと考えます。

**Comment by yenxrutile** [comment]
ご回答ありがとうございます。
おっしゃる通り、ぜまりん氏がZNY関連のグッズやイラスト等を
お披露目する用途で使って頂けると、ご自身にもプロダクトにも
大変良い形になりそうですね。権利関係も説得力があります。
是非折を見て、ご提案して頂ける事を期待しております。

**Comment by hitobb** [comment]
ぜまりんさんとqaleghnesさんの間での会話となりそうです。
（お二人はぜにぃ姫運用開始時期からのお知合いです）
私を含めたBitZeny CoreDev初期メンバーは、客観的に見て第三者の立ち位置に居るのですが、どのようなアクションを取るべきでしょうか？

私としては、上記提案のみを行い、その後の判断はお二人にお任せするのが良いかなと考えます。

いかがでしょう？

**Comment by yenxrutile** [comment]
はい、勿論異論ございません。
今後もし、ぜまりん氏サイドからCoreを頼って何か出来ないか、と言った打診があれば
是非、積極的にバックアップさせて頂きたいと思います。

**Comment by hitobb** [comment]
昨日、上記内容をぜまりんさんにお伝えしました。
qaleghnesさんとコンタクトをとる機会があれば、軽くご相談して頂けるそうです。

本件、クローズとしたいのですが、いかがでしょうか？

**Comment by yenxrutile** [comment]
承知致しました。ご対応ありがとうございます。
