### ISSUE TITLE
ローカライズ対応の案件化

### ISSUE THREAD

**Issue by yenxrutile** [BitzenyCoreDevelopers/others#9]
・バウンティプログラムにしたい

・新サイトのローカライズ

・desktop walletのスペイン語
https://bitzeny.info/d/148-i-request-a-desktop-wallet-translated-into-spanish

**Comment by bellflower2015** [comment]
bitcointalkに新トピを立てて、コミュニティ開発の現状の紹介をしつつ、
ローカライズのバウンティを告知できれば一石二鳥で良さそう。
DiscordやGitHubで呼びかけても見る人は限られるので。

ウォレットのローカライズについては現状どんな感じなんでしょうか？

**Comment by ghost** [comment]
> ウォレットのローカライズについては現状どんな感じなんでしょうか？

日本語と英語を除き未着手

**Comment by hitobb** [comment]
開発がBitZenyPlusに移行しました。
ローカライズにつきましても、BitZenyPlusにて対応します。

https://github.com/bitzenyPlus/

ご検討ありがとうございました。
